
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductLocation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ProductLocation
 * 
 */
export type ProductLocationModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductLocationPayload>

export type AggregateProductLocation = {
  _count: ProductLocationCountAggregateOutputType | null
  _avg: ProductLocationAvgAggregateOutputType | null
  _sum: ProductLocationSumAggregateOutputType | null
  _min: ProductLocationMinAggregateOutputType | null
  _max: ProductLocationMaxAggregateOutputType | null
}

export type ProductLocationAvgAggregateOutputType = {
  quantity: number | null
  reservedQuantity: number | null
}

export type ProductLocationSumAggregateOutputType = {
  quantity: number | null
  reservedQuantity: number | null
}

export type ProductLocationMinAggregateOutputType = {
  id: string | null
  productId: string | null
  warehouseId: string | null
  location: string | null
  quantity: number | null
  reservedQuantity: number | null
  updatedAt: Date | null
  syncedAt: Date | null
  deletedAt: Date | null
  deviceId: string | null
}

export type ProductLocationMaxAggregateOutputType = {
  id: string | null
  productId: string | null
  warehouseId: string | null
  location: string | null
  quantity: number | null
  reservedQuantity: number | null
  updatedAt: Date | null
  syncedAt: Date | null
  deletedAt: Date | null
  deviceId: string | null
}

export type ProductLocationCountAggregateOutputType = {
  id: number
  productId: number
  warehouseId: number
  location: number
  quantity: number
  reservedQuantity: number
  updatedAt: number
  syncedAt: number
  deletedAt: number
  deviceId: number
  _all: number
}


export type ProductLocationAvgAggregateInputType = {
  quantity?: true
  reservedQuantity?: true
}

export type ProductLocationSumAggregateInputType = {
  quantity?: true
  reservedQuantity?: true
}

export type ProductLocationMinAggregateInputType = {
  id?: true
  productId?: true
  warehouseId?: true
  location?: true
  quantity?: true
  reservedQuantity?: true
  updatedAt?: true
  syncedAt?: true
  deletedAt?: true
  deviceId?: true
}

export type ProductLocationMaxAggregateInputType = {
  id?: true
  productId?: true
  warehouseId?: true
  location?: true
  quantity?: true
  reservedQuantity?: true
  updatedAt?: true
  syncedAt?: true
  deletedAt?: true
  deviceId?: true
}

export type ProductLocationCountAggregateInputType = {
  id?: true
  productId?: true
  warehouseId?: true
  location?: true
  quantity?: true
  reservedQuantity?: true
  updatedAt?: true
  syncedAt?: true
  deletedAt?: true
  deviceId?: true
  _all?: true
}

export type ProductLocationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductLocation to aggregate.
   */
  where?: Prisma.ProductLocationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductLocations to fetch.
   */
  orderBy?: Prisma.ProductLocationOrderByWithRelationInput | Prisma.ProductLocationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductLocationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductLocations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductLocations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductLocations
  **/
  _count?: true | ProductLocationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProductLocationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProductLocationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductLocationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductLocationMaxAggregateInputType
}

export type GetProductLocationAggregateType<T extends ProductLocationAggregateArgs> = {
      [P in keyof T & keyof AggregateProductLocation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductLocation[P]>
    : Prisma.GetScalarType<T[P], AggregateProductLocation[P]>
}




export type ProductLocationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductLocationWhereInput
  orderBy?: Prisma.ProductLocationOrderByWithAggregationInput | Prisma.ProductLocationOrderByWithAggregationInput[]
  by: Prisma.ProductLocationScalarFieldEnum[] | Prisma.ProductLocationScalarFieldEnum
  having?: Prisma.ProductLocationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductLocationCountAggregateInputType | true
  _avg?: ProductLocationAvgAggregateInputType
  _sum?: ProductLocationSumAggregateInputType
  _min?: ProductLocationMinAggregateInputType
  _max?: ProductLocationMaxAggregateInputType
}

export type ProductLocationGroupByOutputType = {
  id: string
  productId: string
  warehouseId: string
  location: string | null
  quantity: number
  reservedQuantity: number
  updatedAt: Date
  syncedAt: Date | null
  deletedAt: Date | null
  deviceId: string | null
  _count: ProductLocationCountAggregateOutputType | null
  _avg: ProductLocationAvgAggregateOutputType | null
  _sum: ProductLocationSumAggregateOutputType | null
  _min: ProductLocationMinAggregateOutputType | null
  _max: ProductLocationMaxAggregateOutputType | null
}

type GetProductLocationGroupByPayload<T extends ProductLocationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductLocationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductLocationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductLocationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductLocationGroupByOutputType[P]>
      }
    >
  >



export type ProductLocationWhereInput = {
  AND?: Prisma.ProductLocationWhereInput | Prisma.ProductLocationWhereInput[]
  OR?: Prisma.ProductLocationWhereInput[]
  NOT?: Prisma.ProductLocationWhereInput | Prisma.ProductLocationWhereInput[]
  id?: Prisma.StringFilter<"ProductLocation"> | string
  productId?: Prisma.StringFilter<"ProductLocation"> | string
  warehouseId?: Prisma.StringFilter<"ProductLocation"> | string
  location?: Prisma.StringNullableFilter<"ProductLocation"> | string | null
  quantity?: Prisma.IntFilter<"ProductLocation"> | number
  reservedQuantity?: Prisma.IntFilter<"ProductLocation"> | number
  updatedAt?: Prisma.DateTimeFilter<"ProductLocation"> | Date | string
  syncedAt?: Prisma.DateTimeNullableFilter<"ProductLocation"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"ProductLocation"> | Date | string | null
  deviceId?: Prisma.StringNullableFilter<"ProductLocation"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  warehouse?: Prisma.XOR<Prisma.WarehouseScalarRelationFilter, Prisma.WarehouseWhereInput>
}

export type ProductLocationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  warehouseId?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  quantity?: Prisma.SortOrder
  reservedQuantity?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deviceId?: Prisma.SortOrderInput | Prisma.SortOrder
  product?: Prisma.ProductOrderByWithRelationInput
  warehouse?: Prisma.WarehouseOrderByWithRelationInput
}

export type ProductLocationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  productId_warehouseId?: Prisma.ProductLocationProductIdWarehouseIdCompoundUniqueInput
  AND?: Prisma.ProductLocationWhereInput | Prisma.ProductLocationWhereInput[]
  OR?: Prisma.ProductLocationWhereInput[]
  NOT?: Prisma.ProductLocationWhereInput | Prisma.ProductLocationWhereInput[]
  productId?: Prisma.StringFilter<"ProductLocation"> | string
  warehouseId?: Prisma.StringFilter<"ProductLocation"> | string
  location?: Prisma.StringNullableFilter<"ProductLocation"> | string | null
  quantity?: Prisma.IntFilter<"ProductLocation"> | number
  reservedQuantity?: Prisma.IntFilter<"ProductLocation"> | number
  updatedAt?: Prisma.DateTimeFilter<"ProductLocation"> | Date | string
  syncedAt?: Prisma.DateTimeNullableFilter<"ProductLocation"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"ProductLocation"> | Date | string | null
  deviceId?: Prisma.StringNullableFilter<"ProductLocation"> | string | null
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
  warehouse?: Prisma.XOR<Prisma.WarehouseScalarRelationFilter, Prisma.WarehouseWhereInput>
}, "id" | "productId_warehouseId">

export type ProductLocationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  warehouseId?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  quantity?: Prisma.SortOrder
  reservedQuantity?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deviceId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProductLocationCountOrderByAggregateInput
  _avg?: Prisma.ProductLocationAvgOrderByAggregateInput
  _max?: Prisma.ProductLocationMaxOrderByAggregateInput
  _min?: Prisma.ProductLocationMinOrderByAggregateInput
  _sum?: Prisma.ProductLocationSumOrderByAggregateInput
}

export type ProductLocationScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductLocationScalarWhereWithAggregatesInput | Prisma.ProductLocationScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductLocationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductLocationScalarWhereWithAggregatesInput | Prisma.ProductLocationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductLocation"> | string
  productId?: Prisma.StringWithAggregatesFilter<"ProductLocation"> | string
  warehouseId?: Prisma.StringWithAggregatesFilter<"ProductLocation"> | string
  location?: Prisma.StringNullableWithAggregatesFilter<"ProductLocation"> | string | null
  quantity?: Prisma.IntWithAggregatesFilter<"ProductLocation"> | number
  reservedQuantity?: Prisma.IntWithAggregatesFilter<"ProductLocation"> | number
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ProductLocation"> | Date | string
  syncedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ProductLocation"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ProductLocation"> | Date | string | null
  deviceId?: Prisma.StringNullableWithAggregatesFilter<"ProductLocation"> | string | null
}

export type ProductLocationCreateInput = {
  id?: string
  location?: string | null
  quantity?: number
  reservedQuantity?: number
  updatedAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  product: Prisma.ProductCreateNestedOneWithoutProductLocationsInput
  warehouse: Prisma.WarehouseCreateNestedOneWithoutProductLocationsInput
}

export type ProductLocationUncheckedCreateInput = {
  id?: string
  productId: string
  warehouseId: string
  location?: string | null
  quantity?: number
  reservedQuantity?: number
  updatedAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type ProductLocationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  product?: Prisma.ProductUpdateOneRequiredWithoutProductLocationsNestedInput
  warehouse?: Prisma.WarehouseUpdateOneRequiredWithoutProductLocationsNestedInput
}

export type ProductLocationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  warehouseId?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductLocationCreateManyInput = {
  id?: string
  productId: string
  warehouseId: string
  location?: string | null
  quantity?: number
  reservedQuantity?: number
  updatedAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type ProductLocationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductLocationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  warehouseId?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductLocationListRelationFilter = {
  every?: Prisma.ProductLocationWhereInput
  some?: Prisma.ProductLocationWhereInput
  none?: Prisma.ProductLocationWhereInput
}

export type ProductLocationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductLocationProductIdWarehouseIdCompoundUniqueInput = {
  productId: string
  warehouseId: string
}

export type ProductLocationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  warehouseId?: Prisma.SortOrder
  location?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  reservedQuantity?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
}

export type ProductLocationAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
  reservedQuantity?: Prisma.SortOrder
}

export type ProductLocationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  warehouseId?: Prisma.SortOrder
  location?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  reservedQuantity?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
}

export type ProductLocationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  warehouseId?: Prisma.SortOrder
  location?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  reservedQuantity?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
}

export type ProductLocationSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
  reservedQuantity?: Prisma.SortOrder
}

export type ProductLocationCreateNestedManyWithoutWarehouseInput = {
  create?: Prisma.XOR<Prisma.ProductLocationCreateWithoutWarehouseInput, Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput> | Prisma.ProductLocationCreateWithoutWarehouseInput[] | Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput[]
  connectOrCreate?: Prisma.ProductLocationCreateOrConnectWithoutWarehouseInput | Prisma.ProductLocationCreateOrConnectWithoutWarehouseInput[]
  createMany?: Prisma.ProductLocationCreateManyWarehouseInputEnvelope
  connect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
}

export type ProductLocationUncheckedCreateNestedManyWithoutWarehouseInput = {
  create?: Prisma.XOR<Prisma.ProductLocationCreateWithoutWarehouseInput, Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput> | Prisma.ProductLocationCreateWithoutWarehouseInput[] | Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput[]
  connectOrCreate?: Prisma.ProductLocationCreateOrConnectWithoutWarehouseInput | Prisma.ProductLocationCreateOrConnectWithoutWarehouseInput[]
  createMany?: Prisma.ProductLocationCreateManyWarehouseInputEnvelope
  connect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
}

export type ProductLocationUpdateManyWithoutWarehouseNestedInput = {
  create?: Prisma.XOR<Prisma.ProductLocationCreateWithoutWarehouseInput, Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput> | Prisma.ProductLocationCreateWithoutWarehouseInput[] | Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput[]
  connectOrCreate?: Prisma.ProductLocationCreateOrConnectWithoutWarehouseInput | Prisma.ProductLocationCreateOrConnectWithoutWarehouseInput[]
  upsert?: Prisma.ProductLocationUpsertWithWhereUniqueWithoutWarehouseInput | Prisma.ProductLocationUpsertWithWhereUniqueWithoutWarehouseInput[]
  createMany?: Prisma.ProductLocationCreateManyWarehouseInputEnvelope
  set?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  disconnect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  delete?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  connect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  update?: Prisma.ProductLocationUpdateWithWhereUniqueWithoutWarehouseInput | Prisma.ProductLocationUpdateWithWhereUniqueWithoutWarehouseInput[]
  updateMany?: Prisma.ProductLocationUpdateManyWithWhereWithoutWarehouseInput | Prisma.ProductLocationUpdateManyWithWhereWithoutWarehouseInput[]
  deleteMany?: Prisma.ProductLocationScalarWhereInput | Prisma.ProductLocationScalarWhereInput[]
}

export type ProductLocationUncheckedUpdateManyWithoutWarehouseNestedInput = {
  create?: Prisma.XOR<Prisma.ProductLocationCreateWithoutWarehouseInput, Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput> | Prisma.ProductLocationCreateWithoutWarehouseInput[] | Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput[]
  connectOrCreate?: Prisma.ProductLocationCreateOrConnectWithoutWarehouseInput | Prisma.ProductLocationCreateOrConnectWithoutWarehouseInput[]
  upsert?: Prisma.ProductLocationUpsertWithWhereUniqueWithoutWarehouseInput | Prisma.ProductLocationUpsertWithWhereUniqueWithoutWarehouseInput[]
  createMany?: Prisma.ProductLocationCreateManyWarehouseInputEnvelope
  set?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  disconnect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  delete?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  connect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  update?: Prisma.ProductLocationUpdateWithWhereUniqueWithoutWarehouseInput | Prisma.ProductLocationUpdateWithWhereUniqueWithoutWarehouseInput[]
  updateMany?: Prisma.ProductLocationUpdateManyWithWhereWithoutWarehouseInput | Prisma.ProductLocationUpdateManyWithWhereWithoutWarehouseInput[]
  deleteMany?: Prisma.ProductLocationScalarWhereInput | Prisma.ProductLocationScalarWhereInput[]
}

export type ProductLocationCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductLocationCreateWithoutProductInput, Prisma.ProductLocationUncheckedCreateWithoutProductInput> | Prisma.ProductLocationCreateWithoutProductInput[] | Prisma.ProductLocationUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductLocationCreateOrConnectWithoutProductInput | Prisma.ProductLocationCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductLocationCreateManyProductInputEnvelope
  connect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
}

export type ProductLocationUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.ProductLocationCreateWithoutProductInput, Prisma.ProductLocationUncheckedCreateWithoutProductInput> | Prisma.ProductLocationCreateWithoutProductInput[] | Prisma.ProductLocationUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductLocationCreateOrConnectWithoutProductInput | Prisma.ProductLocationCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.ProductLocationCreateManyProductInputEnvelope
  connect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
}

export type ProductLocationUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductLocationCreateWithoutProductInput, Prisma.ProductLocationUncheckedCreateWithoutProductInput> | Prisma.ProductLocationCreateWithoutProductInput[] | Prisma.ProductLocationUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductLocationCreateOrConnectWithoutProductInput | Prisma.ProductLocationCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductLocationUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductLocationUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductLocationCreateManyProductInputEnvelope
  set?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  disconnect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  delete?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  connect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  update?: Prisma.ProductLocationUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductLocationUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductLocationUpdateManyWithWhereWithoutProductInput | Prisma.ProductLocationUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductLocationScalarWhereInput | Prisma.ProductLocationScalarWhereInput[]
}

export type ProductLocationUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.ProductLocationCreateWithoutProductInput, Prisma.ProductLocationUncheckedCreateWithoutProductInput> | Prisma.ProductLocationCreateWithoutProductInput[] | Prisma.ProductLocationUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.ProductLocationCreateOrConnectWithoutProductInput | Prisma.ProductLocationCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.ProductLocationUpsertWithWhereUniqueWithoutProductInput | Prisma.ProductLocationUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.ProductLocationCreateManyProductInputEnvelope
  set?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  disconnect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  delete?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  connect?: Prisma.ProductLocationWhereUniqueInput | Prisma.ProductLocationWhereUniqueInput[]
  update?: Prisma.ProductLocationUpdateWithWhereUniqueWithoutProductInput | Prisma.ProductLocationUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.ProductLocationUpdateManyWithWhereWithoutProductInput | Prisma.ProductLocationUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.ProductLocationScalarWhereInput | Prisma.ProductLocationScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ProductLocationCreateWithoutWarehouseInput = {
  id?: string
  location?: string | null
  quantity?: number
  reservedQuantity?: number
  updatedAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  product: Prisma.ProductCreateNestedOneWithoutProductLocationsInput
}

export type ProductLocationUncheckedCreateWithoutWarehouseInput = {
  id?: string
  productId: string
  location?: string | null
  quantity?: number
  reservedQuantity?: number
  updatedAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type ProductLocationCreateOrConnectWithoutWarehouseInput = {
  where: Prisma.ProductLocationWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductLocationCreateWithoutWarehouseInput, Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput>
}

export type ProductLocationCreateManyWarehouseInputEnvelope = {
  data: Prisma.ProductLocationCreateManyWarehouseInput | Prisma.ProductLocationCreateManyWarehouseInput[]
  skipDuplicates?: boolean
}

export type ProductLocationUpsertWithWhereUniqueWithoutWarehouseInput = {
  where: Prisma.ProductLocationWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductLocationUpdateWithoutWarehouseInput, Prisma.ProductLocationUncheckedUpdateWithoutWarehouseInput>
  create: Prisma.XOR<Prisma.ProductLocationCreateWithoutWarehouseInput, Prisma.ProductLocationUncheckedCreateWithoutWarehouseInput>
}

export type ProductLocationUpdateWithWhereUniqueWithoutWarehouseInput = {
  where: Prisma.ProductLocationWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductLocationUpdateWithoutWarehouseInput, Prisma.ProductLocationUncheckedUpdateWithoutWarehouseInput>
}

export type ProductLocationUpdateManyWithWhereWithoutWarehouseInput = {
  where: Prisma.ProductLocationScalarWhereInput
  data: Prisma.XOR<Prisma.ProductLocationUpdateManyMutationInput, Prisma.ProductLocationUncheckedUpdateManyWithoutWarehouseInput>
}

export type ProductLocationScalarWhereInput = {
  AND?: Prisma.ProductLocationScalarWhereInput | Prisma.ProductLocationScalarWhereInput[]
  OR?: Prisma.ProductLocationScalarWhereInput[]
  NOT?: Prisma.ProductLocationScalarWhereInput | Prisma.ProductLocationScalarWhereInput[]
  id?: Prisma.StringFilter<"ProductLocation"> | string
  productId?: Prisma.StringFilter<"ProductLocation"> | string
  warehouseId?: Prisma.StringFilter<"ProductLocation"> | string
  location?: Prisma.StringNullableFilter<"ProductLocation"> | string | null
  quantity?: Prisma.IntFilter<"ProductLocation"> | number
  reservedQuantity?: Prisma.IntFilter<"ProductLocation"> | number
  updatedAt?: Prisma.DateTimeFilter<"ProductLocation"> | Date | string
  syncedAt?: Prisma.DateTimeNullableFilter<"ProductLocation"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"ProductLocation"> | Date | string | null
  deviceId?: Prisma.StringNullableFilter<"ProductLocation"> | string | null
}

export type ProductLocationCreateWithoutProductInput = {
  id?: string
  location?: string | null
  quantity?: number
  reservedQuantity?: number
  updatedAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  warehouse: Prisma.WarehouseCreateNestedOneWithoutProductLocationsInput
}

export type ProductLocationUncheckedCreateWithoutProductInput = {
  id?: string
  warehouseId: string
  location?: string | null
  quantity?: number
  reservedQuantity?: number
  updatedAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type ProductLocationCreateOrConnectWithoutProductInput = {
  where: Prisma.ProductLocationWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductLocationCreateWithoutProductInput, Prisma.ProductLocationUncheckedCreateWithoutProductInput>
}

export type ProductLocationCreateManyProductInputEnvelope = {
  data: Prisma.ProductLocationCreateManyProductInput | Prisma.ProductLocationCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type ProductLocationUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductLocationWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductLocationUpdateWithoutProductInput, Prisma.ProductLocationUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.ProductLocationCreateWithoutProductInput, Prisma.ProductLocationUncheckedCreateWithoutProductInput>
}

export type ProductLocationUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.ProductLocationWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductLocationUpdateWithoutProductInput, Prisma.ProductLocationUncheckedUpdateWithoutProductInput>
}

export type ProductLocationUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.ProductLocationScalarWhereInput
  data: Prisma.XOR<Prisma.ProductLocationUpdateManyMutationInput, Prisma.ProductLocationUncheckedUpdateManyWithoutProductInput>
}

export type ProductLocationCreateManyWarehouseInput = {
  id?: string
  productId: string
  location?: string | null
  quantity?: number
  reservedQuantity?: number
  updatedAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type ProductLocationUpdateWithoutWarehouseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  product?: Prisma.ProductUpdateOneRequiredWithoutProductLocationsNestedInput
}

export type ProductLocationUncheckedUpdateWithoutWarehouseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductLocationUncheckedUpdateManyWithoutWarehouseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductLocationCreateManyProductInput = {
  id?: string
  warehouseId: string
  location?: string | null
  quantity?: number
  reservedQuantity?: number
  updatedAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type ProductLocationUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  warehouse?: Prisma.WarehouseUpdateOneRequiredWithoutProductLocationsNestedInput
}

export type ProductLocationUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  warehouseId?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProductLocationUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  warehouseId?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  reservedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ProductLocationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  warehouseId?: boolean
  location?: boolean
  quantity?: boolean
  reservedQuantity?: boolean
  updatedAt?: boolean
  syncedAt?: boolean
  deletedAt?: boolean
  deviceId?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  warehouse?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productLocation"]>

export type ProductLocationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  warehouseId?: boolean
  location?: boolean
  quantity?: boolean
  reservedQuantity?: boolean
  updatedAt?: boolean
  syncedAt?: boolean
  deletedAt?: boolean
  deviceId?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  warehouse?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productLocation"]>

export type ProductLocationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productId?: boolean
  warehouseId?: boolean
  location?: boolean
  quantity?: boolean
  reservedQuantity?: boolean
  updatedAt?: boolean
  syncedAt?: boolean
  deletedAt?: boolean
  deviceId?: boolean
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  warehouse?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productLocation"]>

export type ProductLocationSelectScalar = {
  id?: boolean
  productId?: boolean
  warehouseId?: boolean
  location?: boolean
  quantity?: boolean
  reservedQuantity?: boolean
  updatedAt?: boolean
  syncedAt?: boolean
  deletedAt?: boolean
  deviceId?: boolean
}

export type ProductLocationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productId" | "warehouseId" | "location" | "quantity" | "reservedQuantity" | "updatedAt" | "syncedAt" | "deletedAt" | "deviceId", ExtArgs["result"]["productLocation"]>
export type ProductLocationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  warehouse?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}
export type ProductLocationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  warehouse?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}
export type ProductLocationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
  warehouse?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}

export type $ProductLocationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductLocation"
  objects: {
    product: Prisma.$ProductPayload<ExtArgs>
    warehouse: Prisma.$WarehousePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productId: string
    warehouseId: string
    location: string | null
    quantity: number
    reservedQuantity: number
    updatedAt: Date
    syncedAt: Date | null
    deletedAt: Date | null
    deviceId: string | null
  }, ExtArgs["result"]["productLocation"]>
  composites: {}
}

export type ProductLocationGetPayload<S extends boolean | null | undefined | ProductLocationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload, S>

export type ProductLocationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductLocationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductLocationCountAggregateInputType | true
  }

export interface ProductLocationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductLocation'], meta: { name: 'ProductLocation' } }
  /**
   * Find zero or one ProductLocation that matches the filter.
   * @param {ProductLocationFindUniqueArgs} args - Arguments to find a ProductLocation
   * @example
   * // Get one ProductLocation
   * const productLocation = await prisma.productLocation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductLocationFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductLocationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductLocationClient<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductLocation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductLocationFindUniqueOrThrowArgs} args - Arguments to find a ProductLocation
   * @example
   * // Get one ProductLocation
   * const productLocation = await prisma.productLocation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductLocationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductLocationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductLocationClient<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductLocation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductLocationFindFirstArgs} args - Arguments to find a ProductLocation
   * @example
   * // Get one ProductLocation
   * const productLocation = await prisma.productLocation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductLocationFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductLocationFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductLocationClient<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductLocation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductLocationFindFirstOrThrowArgs} args - Arguments to find a ProductLocation
   * @example
   * // Get one ProductLocation
   * const productLocation = await prisma.productLocation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductLocationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductLocationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductLocationClient<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductLocations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductLocationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductLocations
   * const productLocations = await prisma.productLocation.findMany()
   * 
   * // Get first 10 ProductLocations
   * const productLocations = await prisma.productLocation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productLocationWithIdOnly = await prisma.productLocation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductLocationFindManyArgs>(args?: Prisma.SelectSubset<T, ProductLocationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductLocation.
   * @param {ProductLocationCreateArgs} args - Arguments to create a ProductLocation.
   * @example
   * // Create one ProductLocation
   * const ProductLocation = await prisma.productLocation.create({
   *   data: {
   *     // ... data to create a ProductLocation
   *   }
   * })
   * 
   */
  create<T extends ProductLocationCreateArgs>(args: Prisma.SelectSubset<T, ProductLocationCreateArgs<ExtArgs>>): Prisma.Prisma__ProductLocationClient<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductLocations.
   * @param {ProductLocationCreateManyArgs} args - Arguments to create many ProductLocations.
   * @example
   * // Create many ProductLocations
   * const productLocation = await prisma.productLocation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductLocationCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductLocationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductLocations and returns the data saved in the database.
   * @param {ProductLocationCreateManyAndReturnArgs} args - Arguments to create many ProductLocations.
   * @example
   * // Create many ProductLocations
   * const productLocation = await prisma.productLocation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductLocations and only return the `id`
   * const productLocationWithIdOnly = await prisma.productLocation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductLocationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductLocationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductLocation.
   * @param {ProductLocationDeleteArgs} args - Arguments to delete one ProductLocation.
   * @example
   * // Delete one ProductLocation
   * const ProductLocation = await prisma.productLocation.delete({
   *   where: {
   *     // ... filter to delete one ProductLocation
   *   }
   * })
   * 
   */
  delete<T extends ProductLocationDeleteArgs>(args: Prisma.SelectSubset<T, ProductLocationDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductLocationClient<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductLocation.
   * @param {ProductLocationUpdateArgs} args - Arguments to update one ProductLocation.
   * @example
   * // Update one ProductLocation
   * const productLocation = await prisma.productLocation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductLocationUpdateArgs>(args: Prisma.SelectSubset<T, ProductLocationUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductLocationClient<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductLocations.
   * @param {ProductLocationDeleteManyArgs} args - Arguments to filter ProductLocations to delete.
   * @example
   * // Delete a few ProductLocations
   * const { count } = await prisma.productLocation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductLocationDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductLocationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductLocations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductLocationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductLocations
   * const productLocation = await prisma.productLocation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductLocationUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductLocationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductLocations and returns the data updated in the database.
   * @param {ProductLocationUpdateManyAndReturnArgs} args - Arguments to update many ProductLocations.
   * @example
   * // Update many ProductLocations
   * const productLocation = await prisma.productLocation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductLocations and only return the `id`
   * const productLocationWithIdOnly = await prisma.productLocation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductLocationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductLocationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductLocation.
   * @param {ProductLocationUpsertArgs} args - Arguments to update or create a ProductLocation.
   * @example
   * // Update or create a ProductLocation
   * const productLocation = await prisma.productLocation.upsert({
   *   create: {
   *     // ... data to create a ProductLocation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductLocation we want to update
   *   }
   * })
   */
  upsert<T extends ProductLocationUpsertArgs>(args: Prisma.SelectSubset<T, ProductLocationUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductLocationClient<runtime.Types.Result.GetResult<Prisma.$ProductLocationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductLocations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductLocationCountArgs} args - Arguments to filter ProductLocations to count.
   * @example
   * // Count the number of ProductLocations
   * const count = await prisma.productLocation.count({
   *   where: {
   *     // ... the filter for the ProductLocations we want to count
   *   }
   * })
  **/
  count<T extends ProductLocationCountArgs>(
    args?: Prisma.Subset<T, ProductLocationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductLocationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductLocation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductLocationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductLocationAggregateArgs>(args: Prisma.Subset<T, ProductLocationAggregateArgs>): Prisma.PrismaPromise<GetProductLocationAggregateType<T>>

  /**
   * Group by ProductLocation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductLocationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductLocationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductLocationGroupByArgs['orderBy'] }
      : { orderBy?: ProductLocationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductLocationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductLocationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductLocation model
 */
readonly fields: ProductLocationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductLocation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductLocationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  warehouse<T extends Prisma.WarehouseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WarehouseDefaultArgs<ExtArgs>>): Prisma.Prisma__WarehouseClient<runtime.Types.Result.GetResult<Prisma.$WarehousePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductLocation model
 */
export interface ProductLocationFieldRefs {
  readonly id: Prisma.FieldRef<"ProductLocation", 'String'>
  readonly productId: Prisma.FieldRef<"ProductLocation", 'String'>
  readonly warehouseId: Prisma.FieldRef<"ProductLocation", 'String'>
  readonly location: Prisma.FieldRef<"ProductLocation", 'String'>
  readonly quantity: Prisma.FieldRef<"ProductLocation", 'Int'>
  readonly reservedQuantity: Prisma.FieldRef<"ProductLocation", 'Int'>
  readonly updatedAt: Prisma.FieldRef<"ProductLocation", 'DateTime'>
  readonly syncedAt: Prisma.FieldRef<"ProductLocation", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"ProductLocation", 'DateTime'>
  readonly deviceId: Prisma.FieldRef<"ProductLocation", 'String'>
}
    

// Custom InputTypes
/**
 * ProductLocation findUnique
 */
export type ProductLocationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
  /**
   * Filter, which ProductLocation to fetch.
   */
  where: Prisma.ProductLocationWhereUniqueInput
}

/**
 * ProductLocation findUniqueOrThrow
 */
export type ProductLocationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
  /**
   * Filter, which ProductLocation to fetch.
   */
  where: Prisma.ProductLocationWhereUniqueInput
}

/**
 * ProductLocation findFirst
 */
export type ProductLocationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
  /**
   * Filter, which ProductLocation to fetch.
   */
  where?: Prisma.ProductLocationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductLocations to fetch.
   */
  orderBy?: Prisma.ProductLocationOrderByWithRelationInput | Prisma.ProductLocationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductLocations.
   */
  cursor?: Prisma.ProductLocationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductLocations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductLocations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductLocations.
   */
  distinct?: Prisma.ProductLocationScalarFieldEnum | Prisma.ProductLocationScalarFieldEnum[]
}

/**
 * ProductLocation findFirstOrThrow
 */
export type ProductLocationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
  /**
   * Filter, which ProductLocation to fetch.
   */
  where?: Prisma.ProductLocationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductLocations to fetch.
   */
  orderBy?: Prisma.ProductLocationOrderByWithRelationInput | Prisma.ProductLocationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductLocations.
   */
  cursor?: Prisma.ProductLocationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductLocations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductLocations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductLocations.
   */
  distinct?: Prisma.ProductLocationScalarFieldEnum | Prisma.ProductLocationScalarFieldEnum[]
}

/**
 * ProductLocation findMany
 */
export type ProductLocationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
  /**
   * Filter, which ProductLocations to fetch.
   */
  where?: Prisma.ProductLocationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductLocations to fetch.
   */
  orderBy?: Prisma.ProductLocationOrderByWithRelationInput | Prisma.ProductLocationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductLocations.
   */
  cursor?: Prisma.ProductLocationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductLocations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductLocations.
   */
  skip?: number
  distinct?: Prisma.ProductLocationScalarFieldEnum | Prisma.ProductLocationScalarFieldEnum[]
}

/**
 * ProductLocation create
 */
export type ProductLocationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductLocation.
   */
  data: Prisma.XOR<Prisma.ProductLocationCreateInput, Prisma.ProductLocationUncheckedCreateInput>
}

/**
 * ProductLocation createMany
 */
export type ProductLocationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductLocations.
   */
  data: Prisma.ProductLocationCreateManyInput | Prisma.ProductLocationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductLocation createManyAndReturn
 */
export type ProductLocationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * The data used to create many ProductLocations.
   */
  data: Prisma.ProductLocationCreateManyInput | Prisma.ProductLocationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProductLocation update
 */
export type ProductLocationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductLocation.
   */
  data: Prisma.XOR<Prisma.ProductLocationUpdateInput, Prisma.ProductLocationUncheckedUpdateInput>
  /**
   * Choose, which ProductLocation to update.
   */
  where: Prisma.ProductLocationWhereUniqueInput
}

/**
 * ProductLocation updateMany
 */
export type ProductLocationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductLocations.
   */
  data: Prisma.XOR<Prisma.ProductLocationUpdateManyMutationInput, Prisma.ProductLocationUncheckedUpdateManyInput>
  /**
   * Filter which ProductLocations to update
   */
  where?: Prisma.ProductLocationWhereInput
  /**
   * Limit how many ProductLocations to update.
   */
  limit?: number
}

/**
 * ProductLocation updateManyAndReturn
 */
export type ProductLocationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * The data used to update ProductLocations.
   */
  data: Prisma.XOR<Prisma.ProductLocationUpdateManyMutationInput, Prisma.ProductLocationUncheckedUpdateManyInput>
  /**
   * Filter which ProductLocations to update
   */
  where?: Prisma.ProductLocationWhereInput
  /**
   * Limit how many ProductLocations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProductLocation upsert
 */
export type ProductLocationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductLocation to update in case it exists.
   */
  where: Prisma.ProductLocationWhereUniqueInput
  /**
   * In case the ProductLocation found by the `where` argument doesn't exist, create a new ProductLocation with this data.
   */
  create: Prisma.XOR<Prisma.ProductLocationCreateInput, Prisma.ProductLocationUncheckedCreateInput>
  /**
   * In case the ProductLocation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductLocationUpdateInput, Prisma.ProductLocationUncheckedUpdateInput>
}

/**
 * ProductLocation delete
 */
export type ProductLocationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
  /**
   * Filter which ProductLocation to delete.
   */
  where: Prisma.ProductLocationWhereUniqueInput
}

/**
 * ProductLocation deleteMany
 */
export type ProductLocationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductLocations to delete
   */
  where?: Prisma.ProductLocationWhereInput
  /**
   * Limit how many ProductLocations to delete.
   */
  limit?: number
}

/**
 * ProductLocation without action
 */
export type ProductLocationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductLocation
   */
  select?: Prisma.ProductLocationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductLocation
   */
  omit?: Prisma.ProductLocationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductLocationInclude<ExtArgs> | null
}
