
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TransactionItems` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TransactionItems
 * 
 */
export type TransactionItemsModel = runtime.Types.Result.DefaultSelection<Prisma.$TransactionItemsPayload>

export type AggregateTransactionItems = {
  _count: TransactionItemsCountAggregateOutputType | null
  _avg: TransactionItemsAvgAggregateOutputType | null
  _sum: TransactionItemsSumAggregateOutputType | null
  _min: TransactionItemsMinAggregateOutputType | null
  _max: TransactionItemsMaxAggregateOutputType | null
}

export type TransactionItemsAvgAggregateOutputType = {
  quantity: number | null
}

export type TransactionItemsSumAggregateOutputType = {
  quantity: number | null
}

export type TransactionItemsMinAggregateOutputType = {
  id: string | null
  transactionId: string | null
  productId: string | null
  quantity: number | null
  customerId: string | null
  deletedAt: Date | null
}

export type TransactionItemsMaxAggregateOutputType = {
  id: string | null
  transactionId: string | null
  productId: string | null
  quantity: number | null
  customerId: string | null
  deletedAt: Date | null
}

export type TransactionItemsCountAggregateOutputType = {
  id: number
  transactionId: number
  productId: number
  quantity: number
  customerId: number
  deletedAt: number
  _all: number
}


export type TransactionItemsAvgAggregateInputType = {
  quantity?: true
}

export type TransactionItemsSumAggregateInputType = {
  quantity?: true
}

export type TransactionItemsMinAggregateInputType = {
  id?: true
  transactionId?: true
  productId?: true
  quantity?: true
  customerId?: true
  deletedAt?: true
}

export type TransactionItemsMaxAggregateInputType = {
  id?: true
  transactionId?: true
  productId?: true
  quantity?: true
  customerId?: true
  deletedAt?: true
}

export type TransactionItemsCountAggregateInputType = {
  id?: true
  transactionId?: true
  productId?: true
  quantity?: true
  customerId?: true
  deletedAt?: true
  _all?: true
}

export type TransactionItemsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TransactionItems to aggregate.
   */
  where?: Prisma.TransactionItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionItems to fetch.
   */
  orderBy?: Prisma.TransactionItemsOrderByWithRelationInput | Prisma.TransactionItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TransactionItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TransactionItems
  **/
  _count?: true | TransactionItemsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TransactionItemsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TransactionItemsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TransactionItemsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TransactionItemsMaxAggregateInputType
}

export type GetTransactionItemsAggregateType<T extends TransactionItemsAggregateArgs> = {
      [P in keyof T & keyof AggregateTransactionItems]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTransactionItems[P]>
    : Prisma.GetScalarType<T[P], AggregateTransactionItems[P]>
}




export type TransactionItemsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransactionItemsWhereInput
  orderBy?: Prisma.TransactionItemsOrderByWithAggregationInput | Prisma.TransactionItemsOrderByWithAggregationInput[]
  by: Prisma.TransactionItemsScalarFieldEnum[] | Prisma.TransactionItemsScalarFieldEnum
  having?: Prisma.TransactionItemsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TransactionItemsCountAggregateInputType | true
  _avg?: TransactionItemsAvgAggregateInputType
  _sum?: TransactionItemsSumAggregateInputType
  _min?: TransactionItemsMinAggregateInputType
  _max?: TransactionItemsMaxAggregateInputType
}

export type TransactionItemsGroupByOutputType = {
  id: string
  transactionId: string
  productId: string
  quantity: number
  customerId: string | null
  deletedAt: Date | null
  _count: TransactionItemsCountAggregateOutputType | null
  _avg: TransactionItemsAvgAggregateOutputType | null
  _sum: TransactionItemsSumAggregateOutputType | null
  _min: TransactionItemsMinAggregateOutputType | null
  _max: TransactionItemsMaxAggregateOutputType | null
}

type GetTransactionItemsGroupByPayload<T extends TransactionItemsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TransactionItemsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TransactionItemsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TransactionItemsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TransactionItemsGroupByOutputType[P]>
      }
    >
  >



export type TransactionItemsWhereInput = {
  AND?: Prisma.TransactionItemsWhereInput | Prisma.TransactionItemsWhereInput[]
  OR?: Prisma.TransactionItemsWhereInput[]
  NOT?: Prisma.TransactionItemsWhereInput | Prisma.TransactionItemsWhereInput[]
  id?: Prisma.StringFilter<"TransactionItems"> | string
  transactionId?: Prisma.StringFilter<"TransactionItems"> | string
  productId?: Prisma.StringFilter<"TransactionItems"> | string
  quantity?: Prisma.IntFilter<"TransactionItems"> | number
  customerId?: Prisma.StringNullableFilter<"TransactionItems"> | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"TransactionItems"> | Date | string | null
  transaction?: Prisma.XOR<Prisma.TransactionsScalarRelationFilter, Prisma.TransactionsWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}

export type TransactionItemsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  transaction?: Prisma.TransactionsOrderByWithRelationInput
  product?: Prisma.ProductOrderByWithRelationInput
}

export type TransactionItemsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TransactionItemsWhereInput | Prisma.TransactionItemsWhereInput[]
  OR?: Prisma.TransactionItemsWhereInput[]
  NOT?: Prisma.TransactionItemsWhereInput | Prisma.TransactionItemsWhereInput[]
  transactionId?: Prisma.StringFilter<"TransactionItems"> | string
  productId?: Prisma.StringFilter<"TransactionItems"> | string
  quantity?: Prisma.IntFilter<"TransactionItems"> | number
  customerId?: Prisma.StringNullableFilter<"TransactionItems"> | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"TransactionItems"> | Date | string | null
  transaction?: Prisma.XOR<Prisma.TransactionsScalarRelationFilter, Prisma.TransactionsWhereInput>
  product?: Prisma.XOR<Prisma.ProductScalarRelationFilter, Prisma.ProductWhereInput>
}, "id">

export type TransactionItemsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TransactionItemsCountOrderByAggregateInput
  _avg?: Prisma.TransactionItemsAvgOrderByAggregateInput
  _max?: Prisma.TransactionItemsMaxOrderByAggregateInput
  _min?: Prisma.TransactionItemsMinOrderByAggregateInput
  _sum?: Prisma.TransactionItemsSumOrderByAggregateInput
}

export type TransactionItemsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TransactionItemsScalarWhereWithAggregatesInput | Prisma.TransactionItemsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TransactionItemsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TransactionItemsScalarWhereWithAggregatesInput | Prisma.TransactionItemsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TransactionItems"> | string
  transactionId?: Prisma.StringWithAggregatesFilter<"TransactionItems"> | string
  productId?: Prisma.StringWithAggregatesFilter<"TransactionItems"> | string
  quantity?: Prisma.IntWithAggregatesFilter<"TransactionItems"> | number
  customerId?: Prisma.StringNullableWithAggregatesFilter<"TransactionItems"> | string | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TransactionItems"> | Date | string | null
}

export type TransactionItemsCreateInput = {
  id?: string
  quantity: number
  customerId?: string | null
  deletedAt?: Date | string | null
  transaction: Prisma.TransactionsCreateNestedOneWithoutItemsInput
  product: Prisma.ProductCreateNestedOneWithoutTransactionItemsInput
}

export type TransactionItemsUncheckedCreateInput = {
  id?: string
  transactionId: string
  productId: string
  quantity: number
  customerId?: string | null
  deletedAt?: Date | string | null
}

export type TransactionItemsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  transaction?: Prisma.TransactionsUpdateOneRequiredWithoutItemsNestedInput
  product?: Prisma.ProductUpdateOneRequiredWithoutTransactionItemsNestedInput
}

export type TransactionItemsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransactionItemsCreateManyInput = {
  id?: string
  transactionId: string
  productId: string
  quantity: number
  customerId?: string | null
  deletedAt?: Date | string | null
}

export type TransactionItemsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransactionItemsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransactionItemsListRelationFilter = {
  every?: Prisma.TransactionItemsWhereInput
  some?: Prisma.TransactionItemsWhereInput
  none?: Prisma.TransactionItemsWhereInput
}

export type TransactionItemsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TransactionItemsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TransactionItemsAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type TransactionItemsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TransactionItemsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  productId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type TransactionItemsSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type TransactionItemsCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.TransactionItemsCreateWithoutProductInput, Prisma.TransactionItemsUncheckedCreateWithoutProductInput> | Prisma.TransactionItemsCreateWithoutProductInput[] | Prisma.TransactionItemsUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.TransactionItemsCreateOrConnectWithoutProductInput | Prisma.TransactionItemsCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.TransactionItemsCreateManyProductInputEnvelope
  connect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
}

export type TransactionItemsUncheckedCreateNestedManyWithoutProductInput = {
  create?: Prisma.XOR<Prisma.TransactionItemsCreateWithoutProductInput, Prisma.TransactionItemsUncheckedCreateWithoutProductInput> | Prisma.TransactionItemsCreateWithoutProductInput[] | Prisma.TransactionItemsUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.TransactionItemsCreateOrConnectWithoutProductInput | Prisma.TransactionItemsCreateOrConnectWithoutProductInput[]
  createMany?: Prisma.TransactionItemsCreateManyProductInputEnvelope
  connect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
}

export type TransactionItemsUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionItemsCreateWithoutProductInput, Prisma.TransactionItemsUncheckedCreateWithoutProductInput> | Prisma.TransactionItemsCreateWithoutProductInput[] | Prisma.TransactionItemsUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.TransactionItemsCreateOrConnectWithoutProductInput | Prisma.TransactionItemsCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.TransactionItemsUpsertWithWhereUniqueWithoutProductInput | Prisma.TransactionItemsUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.TransactionItemsCreateManyProductInputEnvelope
  set?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  disconnect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  delete?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  connect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  update?: Prisma.TransactionItemsUpdateWithWhereUniqueWithoutProductInput | Prisma.TransactionItemsUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.TransactionItemsUpdateManyWithWhereWithoutProductInput | Prisma.TransactionItemsUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.TransactionItemsScalarWhereInput | Prisma.TransactionItemsScalarWhereInput[]
}

export type TransactionItemsUncheckedUpdateManyWithoutProductNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionItemsCreateWithoutProductInput, Prisma.TransactionItemsUncheckedCreateWithoutProductInput> | Prisma.TransactionItemsCreateWithoutProductInput[] | Prisma.TransactionItemsUncheckedCreateWithoutProductInput[]
  connectOrCreate?: Prisma.TransactionItemsCreateOrConnectWithoutProductInput | Prisma.TransactionItemsCreateOrConnectWithoutProductInput[]
  upsert?: Prisma.TransactionItemsUpsertWithWhereUniqueWithoutProductInput | Prisma.TransactionItemsUpsertWithWhereUniqueWithoutProductInput[]
  createMany?: Prisma.TransactionItemsCreateManyProductInputEnvelope
  set?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  disconnect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  delete?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  connect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  update?: Prisma.TransactionItemsUpdateWithWhereUniqueWithoutProductInput | Prisma.TransactionItemsUpdateWithWhereUniqueWithoutProductInput[]
  updateMany?: Prisma.TransactionItemsUpdateManyWithWhereWithoutProductInput | Prisma.TransactionItemsUpdateManyWithWhereWithoutProductInput[]
  deleteMany?: Prisma.TransactionItemsScalarWhereInput | Prisma.TransactionItemsScalarWhereInput[]
}

export type TransactionItemsCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.TransactionItemsCreateWithoutTransactionInput, Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput> | Prisma.TransactionItemsCreateWithoutTransactionInput[] | Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransactionItemsCreateOrConnectWithoutTransactionInput | Prisma.TransactionItemsCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.TransactionItemsCreateManyTransactionInputEnvelope
  connect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
}

export type TransactionItemsUncheckedCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.TransactionItemsCreateWithoutTransactionInput, Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput> | Prisma.TransactionItemsCreateWithoutTransactionInput[] | Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransactionItemsCreateOrConnectWithoutTransactionInput | Prisma.TransactionItemsCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.TransactionItemsCreateManyTransactionInputEnvelope
  connect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
}

export type TransactionItemsUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionItemsCreateWithoutTransactionInput, Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput> | Prisma.TransactionItemsCreateWithoutTransactionInput[] | Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransactionItemsCreateOrConnectWithoutTransactionInput | Prisma.TransactionItemsCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.TransactionItemsUpsertWithWhereUniqueWithoutTransactionInput | Prisma.TransactionItemsUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.TransactionItemsCreateManyTransactionInputEnvelope
  set?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  disconnect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  delete?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  connect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  update?: Prisma.TransactionItemsUpdateWithWhereUniqueWithoutTransactionInput | Prisma.TransactionItemsUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.TransactionItemsUpdateManyWithWhereWithoutTransactionInput | Prisma.TransactionItemsUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.TransactionItemsScalarWhereInput | Prisma.TransactionItemsScalarWhereInput[]
}

export type TransactionItemsUncheckedUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionItemsCreateWithoutTransactionInput, Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput> | Prisma.TransactionItemsCreateWithoutTransactionInput[] | Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TransactionItemsCreateOrConnectWithoutTransactionInput | Prisma.TransactionItemsCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.TransactionItemsUpsertWithWhereUniqueWithoutTransactionInput | Prisma.TransactionItemsUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.TransactionItemsCreateManyTransactionInputEnvelope
  set?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  disconnect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  delete?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  connect?: Prisma.TransactionItemsWhereUniqueInput | Prisma.TransactionItemsWhereUniqueInput[]
  update?: Prisma.TransactionItemsUpdateWithWhereUniqueWithoutTransactionInput | Prisma.TransactionItemsUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.TransactionItemsUpdateManyWithWhereWithoutTransactionInput | Prisma.TransactionItemsUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.TransactionItemsScalarWhereInput | Prisma.TransactionItemsScalarWhereInput[]
}

export type TransactionItemsCreateWithoutProductInput = {
  id?: string
  quantity: number
  customerId?: string | null
  deletedAt?: Date | string | null
  transaction: Prisma.TransactionsCreateNestedOneWithoutItemsInput
}

export type TransactionItemsUncheckedCreateWithoutProductInput = {
  id?: string
  transactionId: string
  quantity: number
  customerId?: string | null
  deletedAt?: Date | string | null
}

export type TransactionItemsCreateOrConnectWithoutProductInput = {
  where: Prisma.TransactionItemsWhereUniqueInput
  create: Prisma.XOR<Prisma.TransactionItemsCreateWithoutProductInput, Prisma.TransactionItemsUncheckedCreateWithoutProductInput>
}

export type TransactionItemsCreateManyProductInputEnvelope = {
  data: Prisma.TransactionItemsCreateManyProductInput | Prisma.TransactionItemsCreateManyProductInput[]
  skipDuplicates?: boolean
}

export type TransactionItemsUpsertWithWhereUniqueWithoutProductInput = {
  where: Prisma.TransactionItemsWhereUniqueInput
  update: Prisma.XOR<Prisma.TransactionItemsUpdateWithoutProductInput, Prisma.TransactionItemsUncheckedUpdateWithoutProductInput>
  create: Prisma.XOR<Prisma.TransactionItemsCreateWithoutProductInput, Prisma.TransactionItemsUncheckedCreateWithoutProductInput>
}

export type TransactionItemsUpdateWithWhereUniqueWithoutProductInput = {
  where: Prisma.TransactionItemsWhereUniqueInput
  data: Prisma.XOR<Prisma.TransactionItemsUpdateWithoutProductInput, Prisma.TransactionItemsUncheckedUpdateWithoutProductInput>
}

export type TransactionItemsUpdateManyWithWhereWithoutProductInput = {
  where: Prisma.TransactionItemsScalarWhereInput
  data: Prisma.XOR<Prisma.TransactionItemsUpdateManyMutationInput, Prisma.TransactionItemsUncheckedUpdateManyWithoutProductInput>
}

export type TransactionItemsScalarWhereInput = {
  AND?: Prisma.TransactionItemsScalarWhereInput | Prisma.TransactionItemsScalarWhereInput[]
  OR?: Prisma.TransactionItemsScalarWhereInput[]
  NOT?: Prisma.TransactionItemsScalarWhereInput | Prisma.TransactionItemsScalarWhereInput[]
  id?: Prisma.StringFilter<"TransactionItems"> | string
  transactionId?: Prisma.StringFilter<"TransactionItems"> | string
  productId?: Prisma.StringFilter<"TransactionItems"> | string
  quantity?: Prisma.IntFilter<"TransactionItems"> | number
  customerId?: Prisma.StringNullableFilter<"TransactionItems"> | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"TransactionItems"> | Date | string | null
}

export type TransactionItemsCreateWithoutTransactionInput = {
  id?: string
  quantity: number
  customerId?: string | null
  deletedAt?: Date | string | null
  product: Prisma.ProductCreateNestedOneWithoutTransactionItemsInput
}

export type TransactionItemsUncheckedCreateWithoutTransactionInput = {
  id?: string
  productId: string
  quantity: number
  customerId?: string | null
  deletedAt?: Date | string | null
}

export type TransactionItemsCreateOrConnectWithoutTransactionInput = {
  where: Prisma.TransactionItemsWhereUniqueInput
  create: Prisma.XOR<Prisma.TransactionItemsCreateWithoutTransactionInput, Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput>
}

export type TransactionItemsCreateManyTransactionInputEnvelope = {
  data: Prisma.TransactionItemsCreateManyTransactionInput | Prisma.TransactionItemsCreateManyTransactionInput[]
  skipDuplicates?: boolean
}

export type TransactionItemsUpsertWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.TransactionItemsWhereUniqueInput
  update: Prisma.XOR<Prisma.TransactionItemsUpdateWithoutTransactionInput, Prisma.TransactionItemsUncheckedUpdateWithoutTransactionInput>
  create: Prisma.XOR<Prisma.TransactionItemsCreateWithoutTransactionInput, Prisma.TransactionItemsUncheckedCreateWithoutTransactionInput>
}

export type TransactionItemsUpdateWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.TransactionItemsWhereUniqueInput
  data: Prisma.XOR<Prisma.TransactionItemsUpdateWithoutTransactionInput, Prisma.TransactionItemsUncheckedUpdateWithoutTransactionInput>
}

export type TransactionItemsUpdateManyWithWhereWithoutTransactionInput = {
  where: Prisma.TransactionItemsScalarWhereInput
  data: Prisma.XOR<Prisma.TransactionItemsUpdateManyMutationInput, Prisma.TransactionItemsUncheckedUpdateManyWithoutTransactionInput>
}

export type TransactionItemsCreateManyProductInput = {
  id?: string
  transactionId: string
  quantity: number
  customerId?: string | null
  deletedAt?: Date | string | null
}

export type TransactionItemsUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  transaction?: Prisma.TransactionsUpdateOneRequiredWithoutItemsNestedInput
}

export type TransactionItemsUncheckedUpdateWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransactionItemsUncheckedUpdateManyWithoutProductInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransactionItemsCreateManyTransactionInput = {
  id?: string
  productId: string
  quantity: number
  customerId?: string | null
  deletedAt?: Date | string | null
}

export type TransactionItemsUpdateWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  product?: Prisma.ProductUpdateOneRequiredWithoutTransactionItemsNestedInput
}

export type TransactionItemsUncheckedUpdateWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TransactionItemsUncheckedUpdateManyWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productId?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type TransactionItemsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transactionId?: boolean
  productId?: boolean
  quantity?: boolean
  customerId?: boolean
  deletedAt?: boolean
  transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transactionItems"]>

export type TransactionItemsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transactionId?: boolean
  productId?: boolean
  quantity?: boolean
  customerId?: boolean
  deletedAt?: boolean
  transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transactionItems"]>

export type TransactionItemsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transactionId?: boolean
  productId?: boolean
  quantity?: boolean
  customerId?: boolean
  deletedAt?: boolean
  transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transactionItems"]>

export type TransactionItemsSelectScalar = {
  id?: boolean
  transactionId?: boolean
  productId?: boolean
  quantity?: boolean
  customerId?: boolean
  deletedAt?: boolean
}

export type TransactionItemsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "transactionId" | "productId" | "quantity" | "customerId" | "deletedAt", ExtArgs["result"]["transactionItems"]>
export type TransactionItemsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type TransactionItemsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}
export type TransactionItemsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transaction?: boolean | Prisma.TransactionsDefaultArgs<ExtArgs>
  product?: boolean | Prisma.ProductDefaultArgs<ExtArgs>
}

export type $TransactionItemsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TransactionItems"
  objects: {
    transaction: Prisma.$TransactionsPayload<ExtArgs>
    product: Prisma.$ProductPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    transactionId: string
    productId: string
    quantity: number
    customerId: string | null
    deletedAt: Date | null
  }, ExtArgs["result"]["transactionItems"]>
  composites: {}
}

export type TransactionItemsGetPayload<S extends boolean | null | undefined | TransactionItemsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload, S>

export type TransactionItemsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TransactionItemsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TransactionItemsCountAggregateInputType | true
  }

export interface TransactionItemsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TransactionItems'], meta: { name: 'TransactionItems' } }
  /**
   * Find zero or one TransactionItems that matches the filter.
   * @param {TransactionItemsFindUniqueArgs} args - Arguments to find a TransactionItems
   * @example
   * // Get one TransactionItems
   * const transactionItems = await prisma.transactionItems.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TransactionItemsFindUniqueArgs>(args: Prisma.SelectSubset<T, TransactionItemsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TransactionItemsClient<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TransactionItems that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TransactionItemsFindUniqueOrThrowArgs} args - Arguments to find a TransactionItems
   * @example
   * // Get one TransactionItems
   * const transactionItems = await prisma.transactionItems.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TransactionItemsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TransactionItemsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransactionItemsClient<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TransactionItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionItemsFindFirstArgs} args - Arguments to find a TransactionItems
   * @example
   * // Get one TransactionItems
   * const transactionItems = await prisma.transactionItems.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TransactionItemsFindFirstArgs>(args?: Prisma.SelectSubset<T, TransactionItemsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TransactionItemsClient<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TransactionItems that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionItemsFindFirstOrThrowArgs} args - Arguments to find a TransactionItems
   * @example
   * // Get one TransactionItems
   * const transactionItems = await prisma.transactionItems.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TransactionItemsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TransactionItemsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransactionItemsClient<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TransactionItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionItemsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TransactionItems
   * const transactionItems = await prisma.transactionItems.findMany()
   * 
   * // Get first 10 TransactionItems
   * const transactionItems = await prisma.transactionItems.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const transactionItemsWithIdOnly = await prisma.transactionItems.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TransactionItemsFindManyArgs>(args?: Prisma.SelectSubset<T, TransactionItemsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TransactionItems.
   * @param {TransactionItemsCreateArgs} args - Arguments to create a TransactionItems.
   * @example
   * // Create one TransactionItems
   * const TransactionItems = await prisma.transactionItems.create({
   *   data: {
   *     // ... data to create a TransactionItems
   *   }
   * })
   * 
   */
  create<T extends TransactionItemsCreateArgs>(args: Prisma.SelectSubset<T, TransactionItemsCreateArgs<ExtArgs>>): Prisma.Prisma__TransactionItemsClient<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TransactionItems.
   * @param {TransactionItemsCreateManyArgs} args - Arguments to create many TransactionItems.
   * @example
   * // Create many TransactionItems
   * const transactionItems = await prisma.transactionItems.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TransactionItemsCreateManyArgs>(args?: Prisma.SelectSubset<T, TransactionItemsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TransactionItems and returns the data saved in the database.
   * @param {TransactionItemsCreateManyAndReturnArgs} args - Arguments to create many TransactionItems.
   * @example
   * // Create many TransactionItems
   * const transactionItems = await prisma.transactionItems.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TransactionItems and only return the `id`
   * const transactionItemsWithIdOnly = await prisma.transactionItems.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TransactionItemsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TransactionItemsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TransactionItems.
   * @param {TransactionItemsDeleteArgs} args - Arguments to delete one TransactionItems.
   * @example
   * // Delete one TransactionItems
   * const TransactionItems = await prisma.transactionItems.delete({
   *   where: {
   *     // ... filter to delete one TransactionItems
   *   }
   * })
   * 
   */
  delete<T extends TransactionItemsDeleteArgs>(args: Prisma.SelectSubset<T, TransactionItemsDeleteArgs<ExtArgs>>): Prisma.Prisma__TransactionItemsClient<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TransactionItems.
   * @param {TransactionItemsUpdateArgs} args - Arguments to update one TransactionItems.
   * @example
   * // Update one TransactionItems
   * const transactionItems = await prisma.transactionItems.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TransactionItemsUpdateArgs>(args: Prisma.SelectSubset<T, TransactionItemsUpdateArgs<ExtArgs>>): Prisma.Prisma__TransactionItemsClient<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TransactionItems.
   * @param {TransactionItemsDeleteManyArgs} args - Arguments to filter TransactionItems to delete.
   * @example
   * // Delete a few TransactionItems
   * const { count } = await prisma.transactionItems.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TransactionItemsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TransactionItemsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TransactionItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionItemsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TransactionItems
   * const transactionItems = await prisma.transactionItems.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TransactionItemsUpdateManyArgs>(args: Prisma.SelectSubset<T, TransactionItemsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TransactionItems and returns the data updated in the database.
   * @param {TransactionItemsUpdateManyAndReturnArgs} args - Arguments to update many TransactionItems.
   * @example
   * // Update many TransactionItems
   * const transactionItems = await prisma.transactionItems.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TransactionItems and only return the `id`
   * const transactionItemsWithIdOnly = await prisma.transactionItems.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TransactionItemsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TransactionItemsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TransactionItems.
   * @param {TransactionItemsUpsertArgs} args - Arguments to update or create a TransactionItems.
   * @example
   * // Update or create a TransactionItems
   * const transactionItems = await prisma.transactionItems.upsert({
   *   create: {
   *     // ... data to create a TransactionItems
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TransactionItems we want to update
   *   }
   * })
   */
  upsert<T extends TransactionItemsUpsertArgs>(args: Prisma.SelectSubset<T, TransactionItemsUpsertArgs<ExtArgs>>): Prisma.Prisma__TransactionItemsClient<runtime.Types.Result.GetResult<Prisma.$TransactionItemsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TransactionItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionItemsCountArgs} args - Arguments to filter TransactionItems to count.
   * @example
   * // Count the number of TransactionItems
   * const count = await prisma.transactionItems.count({
   *   where: {
   *     // ... the filter for the TransactionItems we want to count
   *   }
   * })
  **/
  count<T extends TransactionItemsCountArgs>(
    args?: Prisma.Subset<T, TransactionItemsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TransactionItemsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TransactionItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionItemsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TransactionItemsAggregateArgs>(args: Prisma.Subset<T, TransactionItemsAggregateArgs>): Prisma.PrismaPromise<GetTransactionItemsAggregateType<T>>

  /**
   * Group by TransactionItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionItemsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TransactionItemsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TransactionItemsGroupByArgs['orderBy'] }
      : { orderBy?: TransactionItemsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TransactionItemsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTransactionItemsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TransactionItems model
 */
readonly fields: TransactionItemsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TransactionItems.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TransactionItemsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  transaction<T extends Prisma.TransactionsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TransactionsDefaultArgs<ExtArgs>>): Prisma.Prisma__TransactionsClient<runtime.Types.Result.GetResult<Prisma.$TransactionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  product<T extends Prisma.ProductDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductClient<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TransactionItems model
 */
export interface TransactionItemsFieldRefs {
  readonly id: Prisma.FieldRef<"TransactionItems", 'String'>
  readonly transactionId: Prisma.FieldRef<"TransactionItems", 'String'>
  readonly productId: Prisma.FieldRef<"TransactionItems", 'String'>
  readonly quantity: Prisma.FieldRef<"TransactionItems", 'Int'>
  readonly customerId: Prisma.FieldRef<"TransactionItems", 'String'>
  readonly deletedAt: Prisma.FieldRef<"TransactionItems", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TransactionItems findUnique
 */
export type TransactionItemsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
  /**
   * Filter, which TransactionItems to fetch.
   */
  where: Prisma.TransactionItemsWhereUniqueInput
}

/**
 * TransactionItems findUniqueOrThrow
 */
export type TransactionItemsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
  /**
   * Filter, which TransactionItems to fetch.
   */
  where: Prisma.TransactionItemsWhereUniqueInput
}

/**
 * TransactionItems findFirst
 */
export type TransactionItemsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
  /**
   * Filter, which TransactionItems to fetch.
   */
  where?: Prisma.TransactionItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionItems to fetch.
   */
  orderBy?: Prisma.TransactionItemsOrderByWithRelationInput | Prisma.TransactionItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TransactionItems.
   */
  cursor?: Prisma.TransactionItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TransactionItems.
   */
  distinct?: Prisma.TransactionItemsScalarFieldEnum | Prisma.TransactionItemsScalarFieldEnum[]
}

/**
 * TransactionItems findFirstOrThrow
 */
export type TransactionItemsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
  /**
   * Filter, which TransactionItems to fetch.
   */
  where?: Prisma.TransactionItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionItems to fetch.
   */
  orderBy?: Prisma.TransactionItemsOrderByWithRelationInput | Prisma.TransactionItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TransactionItems.
   */
  cursor?: Prisma.TransactionItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TransactionItems.
   */
  distinct?: Prisma.TransactionItemsScalarFieldEnum | Prisma.TransactionItemsScalarFieldEnum[]
}

/**
 * TransactionItems findMany
 */
export type TransactionItemsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
  /**
   * Filter, which TransactionItems to fetch.
   */
  where?: Prisma.TransactionItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionItems to fetch.
   */
  orderBy?: Prisma.TransactionItemsOrderByWithRelationInput | Prisma.TransactionItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TransactionItems.
   */
  cursor?: Prisma.TransactionItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionItems.
   */
  skip?: number
  distinct?: Prisma.TransactionItemsScalarFieldEnum | Prisma.TransactionItemsScalarFieldEnum[]
}

/**
 * TransactionItems create
 */
export type TransactionItemsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
  /**
   * The data needed to create a TransactionItems.
   */
  data: Prisma.XOR<Prisma.TransactionItemsCreateInput, Prisma.TransactionItemsUncheckedCreateInput>
}

/**
 * TransactionItems createMany
 */
export type TransactionItemsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TransactionItems.
   */
  data: Prisma.TransactionItemsCreateManyInput | Prisma.TransactionItemsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TransactionItems createManyAndReturn
 */
export type TransactionItemsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * The data used to create many TransactionItems.
   */
  data: Prisma.TransactionItemsCreateManyInput | Prisma.TransactionItemsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TransactionItems update
 */
export type TransactionItemsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
  /**
   * The data needed to update a TransactionItems.
   */
  data: Prisma.XOR<Prisma.TransactionItemsUpdateInput, Prisma.TransactionItemsUncheckedUpdateInput>
  /**
   * Choose, which TransactionItems to update.
   */
  where: Prisma.TransactionItemsWhereUniqueInput
}

/**
 * TransactionItems updateMany
 */
export type TransactionItemsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TransactionItems.
   */
  data: Prisma.XOR<Prisma.TransactionItemsUpdateManyMutationInput, Prisma.TransactionItemsUncheckedUpdateManyInput>
  /**
   * Filter which TransactionItems to update
   */
  where?: Prisma.TransactionItemsWhereInput
  /**
   * Limit how many TransactionItems to update.
   */
  limit?: number
}

/**
 * TransactionItems updateManyAndReturn
 */
export type TransactionItemsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * The data used to update TransactionItems.
   */
  data: Prisma.XOR<Prisma.TransactionItemsUpdateManyMutationInput, Prisma.TransactionItemsUncheckedUpdateManyInput>
  /**
   * Filter which TransactionItems to update
   */
  where?: Prisma.TransactionItemsWhereInput
  /**
   * Limit how many TransactionItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TransactionItems upsert
 */
export type TransactionItemsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
  /**
   * The filter to search for the TransactionItems to update in case it exists.
   */
  where: Prisma.TransactionItemsWhereUniqueInput
  /**
   * In case the TransactionItems found by the `where` argument doesn't exist, create a new TransactionItems with this data.
   */
  create: Prisma.XOR<Prisma.TransactionItemsCreateInput, Prisma.TransactionItemsUncheckedCreateInput>
  /**
   * In case the TransactionItems was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TransactionItemsUpdateInput, Prisma.TransactionItemsUncheckedUpdateInput>
}

/**
 * TransactionItems delete
 */
export type TransactionItemsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
  /**
   * Filter which TransactionItems to delete.
   */
  where: Prisma.TransactionItemsWhereUniqueInput
}

/**
 * TransactionItems deleteMany
 */
export type TransactionItemsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TransactionItems to delete
   */
  where?: Prisma.TransactionItemsWhereInput
  /**
   * Limit how many TransactionItems to delete.
   */
  limit?: number
}

/**
 * TransactionItems without action
 */
export type TransactionItemsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionItems
   */
  select?: Prisma.TransactionItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionItems
   */
  omit?: Prisma.TransactionItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionItemsInclude<ExtArgs> | null
}
