
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TransferRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TransferRequest
 * 
 */
export type TransferRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$TransferRequestPayload>

export type AggregateTransferRequest = {
  _count: TransferRequestCountAggregateOutputType | null
  _min: TransferRequestMinAggregateOutputType | null
  _max: TransferRequestMaxAggregateOutputType | null
}

export type TransferRequestMinAggregateOutputType = {
  id: string | null
  sourceId: string | null
  destinationId: string | null
  reference: string | null
  note: string | null
  createdAt: Date | null
  syncedAt: Date | null
  deletedAt: Date | null
  deviceId: string | null
}

export type TransferRequestMaxAggregateOutputType = {
  id: string | null
  sourceId: string | null
  destinationId: string | null
  reference: string | null
  note: string | null
  createdAt: Date | null
  syncedAt: Date | null
  deletedAt: Date | null
  deviceId: string | null
}

export type TransferRequestCountAggregateOutputType = {
  id: number
  sourceId: number
  destinationId: number
  reference: number
  note: number
  createdAt: number
  syncedAt: number
  deletedAt: number
  deviceId: number
  _all: number
}


export type TransferRequestMinAggregateInputType = {
  id?: true
  sourceId?: true
  destinationId?: true
  reference?: true
  note?: true
  createdAt?: true
  syncedAt?: true
  deletedAt?: true
  deviceId?: true
}

export type TransferRequestMaxAggregateInputType = {
  id?: true
  sourceId?: true
  destinationId?: true
  reference?: true
  note?: true
  createdAt?: true
  syncedAt?: true
  deletedAt?: true
  deviceId?: true
}

export type TransferRequestCountAggregateInputType = {
  id?: true
  sourceId?: true
  destinationId?: true
  reference?: true
  note?: true
  createdAt?: true
  syncedAt?: true
  deletedAt?: true
  deviceId?: true
  _all?: true
}

export type TransferRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TransferRequest to aggregate.
   */
  where?: Prisma.TransferRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransferRequests to fetch.
   */
  orderBy?: Prisma.TransferRequestOrderByWithRelationInput | Prisma.TransferRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TransferRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransferRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransferRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TransferRequests
  **/
  _count?: true | TransferRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TransferRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TransferRequestMaxAggregateInputType
}

export type GetTransferRequestAggregateType<T extends TransferRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateTransferRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTransferRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateTransferRequest[P]>
}




export type TransferRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransferRequestWhereInput
  orderBy?: Prisma.TransferRequestOrderByWithAggregationInput | Prisma.TransferRequestOrderByWithAggregationInput[]
  by: Prisma.TransferRequestScalarFieldEnum[] | Prisma.TransferRequestScalarFieldEnum
  having?: Prisma.TransferRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TransferRequestCountAggregateInputType | true
  _min?: TransferRequestMinAggregateInputType
  _max?: TransferRequestMaxAggregateInputType
}

export type TransferRequestGroupByOutputType = {
  id: string
  sourceId: string
  destinationId: string
  reference: string
  note: string | null
  createdAt: Date
  syncedAt: Date | null
  deletedAt: Date | null
  deviceId: string | null
  _count: TransferRequestCountAggregateOutputType | null
  _min: TransferRequestMinAggregateOutputType | null
  _max: TransferRequestMaxAggregateOutputType | null
}

type GetTransferRequestGroupByPayload<T extends TransferRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TransferRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TransferRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TransferRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TransferRequestGroupByOutputType[P]>
      }
    >
  >



export type TransferRequestWhereInput = {
  AND?: Prisma.TransferRequestWhereInput | Prisma.TransferRequestWhereInput[]
  OR?: Prisma.TransferRequestWhereInput[]
  NOT?: Prisma.TransferRequestWhereInput | Prisma.TransferRequestWhereInput[]
  id?: Prisma.StringFilter<"TransferRequest"> | string
  sourceId?: Prisma.StringFilter<"TransferRequest"> | string
  destinationId?: Prisma.StringFilter<"TransferRequest"> | string
  reference?: Prisma.StringFilter<"TransferRequest"> | string
  note?: Prisma.StringNullableFilter<"TransferRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TransferRequest"> | Date | string
  syncedAt?: Prisma.DateTimeNullableFilter<"TransferRequest"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"TransferRequest"> | Date | string | null
  deviceId?: Prisma.StringNullableFilter<"TransferRequest"> | string | null
  source?: Prisma.XOR<Prisma.WarehouseScalarRelationFilter, Prisma.WarehouseWhereInput>
  destination?: Prisma.XOR<Prisma.WarehouseScalarRelationFilter, Prisma.WarehouseWhereInput>
  items?: Prisma.TransferItemListRelationFilter
}

export type TransferRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deviceId?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.WarehouseOrderByWithRelationInput
  destination?: Prisma.WarehouseOrderByWithRelationInput
  items?: Prisma.TransferItemOrderByRelationAggregateInput
}

export type TransferRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  reference?: string
  AND?: Prisma.TransferRequestWhereInput | Prisma.TransferRequestWhereInput[]
  OR?: Prisma.TransferRequestWhereInput[]
  NOT?: Prisma.TransferRequestWhereInput | Prisma.TransferRequestWhereInput[]
  sourceId?: Prisma.StringFilter<"TransferRequest"> | string
  destinationId?: Prisma.StringFilter<"TransferRequest"> | string
  note?: Prisma.StringNullableFilter<"TransferRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TransferRequest"> | Date | string
  syncedAt?: Prisma.DateTimeNullableFilter<"TransferRequest"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"TransferRequest"> | Date | string | null
  deviceId?: Prisma.StringNullableFilter<"TransferRequest"> | string | null
  source?: Prisma.XOR<Prisma.WarehouseScalarRelationFilter, Prisma.WarehouseWhereInput>
  destination?: Prisma.XOR<Prisma.WarehouseScalarRelationFilter, Prisma.WarehouseWhereInput>
  items?: Prisma.TransferItemListRelationFilter
}, "id" | "reference">

export type TransferRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  deviceId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TransferRequestCountOrderByAggregateInput
  _max?: Prisma.TransferRequestMaxOrderByAggregateInput
  _min?: Prisma.TransferRequestMinOrderByAggregateInput
}

export type TransferRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.TransferRequestScalarWhereWithAggregatesInput | Prisma.TransferRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.TransferRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TransferRequestScalarWhereWithAggregatesInput | Prisma.TransferRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TransferRequest"> | string
  sourceId?: Prisma.StringWithAggregatesFilter<"TransferRequest"> | string
  destinationId?: Prisma.StringWithAggregatesFilter<"TransferRequest"> | string
  reference?: Prisma.StringWithAggregatesFilter<"TransferRequest"> | string
  note?: Prisma.StringNullableWithAggregatesFilter<"TransferRequest"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TransferRequest"> | Date | string
  syncedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TransferRequest"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"TransferRequest"> | Date | string | null
  deviceId?: Prisma.StringNullableWithAggregatesFilter<"TransferRequest"> | string | null
}

export type TransferRequestCreateInput = {
  id?: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  source: Prisma.WarehouseCreateNestedOneWithoutTransferRequestsSourceInput
  destination: Prisma.WarehouseCreateNestedOneWithoutTransferRequestsDestinationInput
  items?: Prisma.TransferItemCreateNestedManyWithoutTransferInput
}

export type TransferRequestUncheckedCreateInput = {
  id?: string
  sourceId: string
  destinationId: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  items?: Prisma.TransferItemUncheckedCreateNestedManyWithoutTransferInput
}

export type TransferRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.WarehouseUpdateOneRequiredWithoutTransferRequestsSourceNestedInput
  destination?: Prisma.WarehouseUpdateOneRequiredWithoutTransferRequestsDestinationNestedInput
  items?: Prisma.TransferItemUpdateManyWithoutTransferNestedInput
}

export type TransferRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  items?: Prisma.TransferItemUncheckedUpdateManyWithoutTransferNestedInput
}

export type TransferRequestCreateManyInput = {
  id?: string
  sourceId: string
  destinationId: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type TransferRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TransferRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TransferRequestListRelationFilter = {
  every?: Prisma.TransferRequestWhereInput
  some?: Prisma.TransferRequestWhereInput
  none?: Prisma.TransferRequestWhereInput
}

export type TransferRequestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TransferRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
}

export type TransferRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
}

export type TransferRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sourceId?: Prisma.SortOrder
  destinationId?: Prisma.SortOrder
  reference?: Prisma.SortOrder
  note?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  deviceId?: Prisma.SortOrder
}

export type TransferRequestScalarRelationFilter = {
  is?: Prisma.TransferRequestWhereInput
  isNot?: Prisma.TransferRequestWhereInput
}

export type TransferRequestCreateNestedManyWithoutSourceInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutSourceInput, Prisma.TransferRequestUncheckedCreateWithoutSourceInput> | Prisma.TransferRequestCreateWithoutSourceInput[] | Prisma.TransferRequestUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutSourceInput | Prisma.TransferRequestCreateOrConnectWithoutSourceInput[]
  createMany?: Prisma.TransferRequestCreateManySourceInputEnvelope
  connect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
}

export type TransferRequestCreateNestedManyWithoutDestinationInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutDestinationInput, Prisma.TransferRequestUncheckedCreateWithoutDestinationInput> | Prisma.TransferRequestCreateWithoutDestinationInput[] | Prisma.TransferRequestUncheckedCreateWithoutDestinationInput[]
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutDestinationInput | Prisma.TransferRequestCreateOrConnectWithoutDestinationInput[]
  createMany?: Prisma.TransferRequestCreateManyDestinationInputEnvelope
  connect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
}

export type TransferRequestUncheckedCreateNestedManyWithoutSourceInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutSourceInput, Prisma.TransferRequestUncheckedCreateWithoutSourceInput> | Prisma.TransferRequestCreateWithoutSourceInput[] | Prisma.TransferRequestUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutSourceInput | Prisma.TransferRequestCreateOrConnectWithoutSourceInput[]
  createMany?: Prisma.TransferRequestCreateManySourceInputEnvelope
  connect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
}

export type TransferRequestUncheckedCreateNestedManyWithoutDestinationInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutDestinationInput, Prisma.TransferRequestUncheckedCreateWithoutDestinationInput> | Prisma.TransferRequestCreateWithoutDestinationInput[] | Prisma.TransferRequestUncheckedCreateWithoutDestinationInput[]
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutDestinationInput | Prisma.TransferRequestCreateOrConnectWithoutDestinationInput[]
  createMany?: Prisma.TransferRequestCreateManyDestinationInputEnvelope
  connect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
}

export type TransferRequestUpdateManyWithoutSourceNestedInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutSourceInput, Prisma.TransferRequestUncheckedCreateWithoutSourceInput> | Prisma.TransferRequestCreateWithoutSourceInput[] | Prisma.TransferRequestUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutSourceInput | Prisma.TransferRequestCreateOrConnectWithoutSourceInput[]
  upsert?: Prisma.TransferRequestUpsertWithWhereUniqueWithoutSourceInput | Prisma.TransferRequestUpsertWithWhereUniqueWithoutSourceInput[]
  createMany?: Prisma.TransferRequestCreateManySourceInputEnvelope
  set?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  disconnect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  delete?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  connect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  update?: Prisma.TransferRequestUpdateWithWhereUniqueWithoutSourceInput | Prisma.TransferRequestUpdateWithWhereUniqueWithoutSourceInput[]
  updateMany?: Prisma.TransferRequestUpdateManyWithWhereWithoutSourceInput | Prisma.TransferRequestUpdateManyWithWhereWithoutSourceInput[]
  deleteMany?: Prisma.TransferRequestScalarWhereInput | Prisma.TransferRequestScalarWhereInput[]
}

export type TransferRequestUpdateManyWithoutDestinationNestedInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutDestinationInput, Prisma.TransferRequestUncheckedCreateWithoutDestinationInput> | Prisma.TransferRequestCreateWithoutDestinationInput[] | Prisma.TransferRequestUncheckedCreateWithoutDestinationInput[]
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutDestinationInput | Prisma.TransferRequestCreateOrConnectWithoutDestinationInput[]
  upsert?: Prisma.TransferRequestUpsertWithWhereUniqueWithoutDestinationInput | Prisma.TransferRequestUpsertWithWhereUniqueWithoutDestinationInput[]
  createMany?: Prisma.TransferRequestCreateManyDestinationInputEnvelope
  set?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  disconnect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  delete?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  connect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  update?: Prisma.TransferRequestUpdateWithWhereUniqueWithoutDestinationInput | Prisma.TransferRequestUpdateWithWhereUniqueWithoutDestinationInput[]
  updateMany?: Prisma.TransferRequestUpdateManyWithWhereWithoutDestinationInput | Prisma.TransferRequestUpdateManyWithWhereWithoutDestinationInput[]
  deleteMany?: Prisma.TransferRequestScalarWhereInput | Prisma.TransferRequestScalarWhereInput[]
}

export type TransferRequestUncheckedUpdateManyWithoutSourceNestedInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutSourceInput, Prisma.TransferRequestUncheckedCreateWithoutSourceInput> | Prisma.TransferRequestCreateWithoutSourceInput[] | Prisma.TransferRequestUncheckedCreateWithoutSourceInput[]
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutSourceInput | Prisma.TransferRequestCreateOrConnectWithoutSourceInput[]
  upsert?: Prisma.TransferRequestUpsertWithWhereUniqueWithoutSourceInput | Prisma.TransferRequestUpsertWithWhereUniqueWithoutSourceInput[]
  createMany?: Prisma.TransferRequestCreateManySourceInputEnvelope
  set?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  disconnect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  delete?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  connect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  update?: Prisma.TransferRequestUpdateWithWhereUniqueWithoutSourceInput | Prisma.TransferRequestUpdateWithWhereUniqueWithoutSourceInput[]
  updateMany?: Prisma.TransferRequestUpdateManyWithWhereWithoutSourceInput | Prisma.TransferRequestUpdateManyWithWhereWithoutSourceInput[]
  deleteMany?: Prisma.TransferRequestScalarWhereInput | Prisma.TransferRequestScalarWhereInput[]
}

export type TransferRequestUncheckedUpdateManyWithoutDestinationNestedInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutDestinationInput, Prisma.TransferRequestUncheckedCreateWithoutDestinationInput> | Prisma.TransferRequestCreateWithoutDestinationInput[] | Prisma.TransferRequestUncheckedCreateWithoutDestinationInput[]
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutDestinationInput | Prisma.TransferRequestCreateOrConnectWithoutDestinationInput[]
  upsert?: Prisma.TransferRequestUpsertWithWhereUniqueWithoutDestinationInput | Prisma.TransferRequestUpsertWithWhereUniqueWithoutDestinationInput[]
  createMany?: Prisma.TransferRequestCreateManyDestinationInputEnvelope
  set?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  disconnect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  delete?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  connect?: Prisma.TransferRequestWhereUniqueInput | Prisma.TransferRequestWhereUniqueInput[]
  update?: Prisma.TransferRequestUpdateWithWhereUniqueWithoutDestinationInput | Prisma.TransferRequestUpdateWithWhereUniqueWithoutDestinationInput[]
  updateMany?: Prisma.TransferRequestUpdateManyWithWhereWithoutDestinationInput | Prisma.TransferRequestUpdateManyWithWhereWithoutDestinationInput[]
  deleteMany?: Prisma.TransferRequestScalarWhereInput | Prisma.TransferRequestScalarWhereInput[]
}

export type TransferRequestCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutItemsInput, Prisma.TransferRequestUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutItemsInput
  connect?: Prisma.TransferRequestWhereUniqueInput
}

export type TransferRequestUpdateOneRequiredWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.TransferRequestCreateWithoutItemsInput, Prisma.TransferRequestUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.TransferRequestCreateOrConnectWithoutItemsInput
  upsert?: Prisma.TransferRequestUpsertWithoutItemsInput
  connect?: Prisma.TransferRequestWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TransferRequestUpdateToOneWithWhereWithoutItemsInput, Prisma.TransferRequestUpdateWithoutItemsInput>, Prisma.TransferRequestUncheckedUpdateWithoutItemsInput>
}

export type TransferRequestCreateWithoutSourceInput = {
  id?: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  destination: Prisma.WarehouseCreateNestedOneWithoutTransferRequestsDestinationInput
  items?: Prisma.TransferItemCreateNestedManyWithoutTransferInput
}

export type TransferRequestUncheckedCreateWithoutSourceInput = {
  id?: string
  destinationId: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  items?: Prisma.TransferItemUncheckedCreateNestedManyWithoutTransferInput
}

export type TransferRequestCreateOrConnectWithoutSourceInput = {
  where: Prisma.TransferRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.TransferRequestCreateWithoutSourceInput, Prisma.TransferRequestUncheckedCreateWithoutSourceInput>
}

export type TransferRequestCreateManySourceInputEnvelope = {
  data: Prisma.TransferRequestCreateManySourceInput | Prisma.TransferRequestCreateManySourceInput[]
  skipDuplicates?: boolean
}

export type TransferRequestCreateWithoutDestinationInput = {
  id?: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  source: Prisma.WarehouseCreateNestedOneWithoutTransferRequestsSourceInput
  items?: Prisma.TransferItemCreateNestedManyWithoutTransferInput
}

export type TransferRequestUncheckedCreateWithoutDestinationInput = {
  id?: string
  sourceId: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  items?: Prisma.TransferItemUncheckedCreateNestedManyWithoutTransferInput
}

export type TransferRequestCreateOrConnectWithoutDestinationInput = {
  where: Prisma.TransferRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.TransferRequestCreateWithoutDestinationInput, Prisma.TransferRequestUncheckedCreateWithoutDestinationInput>
}

export type TransferRequestCreateManyDestinationInputEnvelope = {
  data: Prisma.TransferRequestCreateManyDestinationInput | Prisma.TransferRequestCreateManyDestinationInput[]
  skipDuplicates?: boolean
}

export type TransferRequestUpsertWithWhereUniqueWithoutSourceInput = {
  where: Prisma.TransferRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.TransferRequestUpdateWithoutSourceInput, Prisma.TransferRequestUncheckedUpdateWithoutSourceInput>
  create: Prisma.XOR<Prisma.TransferRequestCreateWithoutSourceInput, Prisma.TransferRequestUncheckedCreateWithoutSourceInput>
}

export type TransferRequestUpdateWithWhereUniqueWithoutSourceInput = {
  where: Prisma.TransferRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.TransferRequestUpdateWithoutSourceInput, Prisma.TransferRequestUncheckedUpdateWithoutSourceInput>
}

export type TransferRequestUpdateManyWithWhereWithoutSourceInput = {
  where: Prisma.TransferRequestScalarWhereInput
  data: Prisma.XOR<Prisma.TransferRequestUpdateManyMutationInput, Prisma.TransferRequestUncheckedUpdateManyWithoutSourceInput>
}

export type TransferRequestScalarWhereInput = {
  AND?: Prisma.TransferRequestScalarWhereInput | Prisma.TransferRequestScalarWhereInput[]
  OR?: Prisma.TransferRequestScalarWhereInput[]
  NOT?: Prisma.TransferRequestScalarWhereInput | Prisma.TransferRequestScalarWhereInput[]
  id?: Prisma.StringFilter<"TransferRequest"> | string
  sourceId?: Prisma.StringFilter<"TransferRequest"> | string
  destinationId?: Prisma.StringFilter<"TransferRequest"> | string
  reference?: Prisma.StringFilter<"TransferRequest"> | string
  note?: Prisma.StringNullableFilter<"TransferRequest"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TransferRequest"> | Date | string
  syncedAt?: Prisma.DateTimeNullableFilter<"TransferRequest"> | Date | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"TransferRequest"> | Date | string | null
  deviceId?: Prisma.StringNullableFilter<"TransferRequest"> | string | null
}

export type TransferRequestUpsertWithWhereUniqueWithoutDestinationInput = {
  where: Prisma.TransferRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.TransferRequestUpdateWithoutDestinationInput, Prisma.TransferRequestUncheckedUpdateWithoutDestinationInput>
  create: Prisma.XOR<Prisma.TransferRequestCreateWithoutDestinationInput, Prisma.TransferRequestUncheckedCreateWithoutDestinationInput>
}

export type TransferRequestUpdateWithWhereUniqueWithoutDestinationInput = {
  where: Prisma.TransferRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.TransferRequestUpdateWithoutDestinationInput, Prisma.TransferRequestUncheckedUpdateWithoutDestinationInput>
}

export type TransferRequestUpdateManyWithWhereWithoutDestinationInput = {
  where: Prisma.TransferRequestScalarWhereInput
  data: Prisma.XOR<Prisma.TransferRequestUpdateManyMutationInput, Prisma.TransferRequestUncheckedUpdateManyWithoutDestinationInput>
}

export type TransferRequestCreateWithoutItemsInput = {
  id?: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
  source: Prisma.WarehouseCreateNestedOneWithoutTransferRequestsSourceInput
  destination: Prisma.WarehouseCreateNestedOneWithoutTransferRequestsDestinationInput
}

export type TransferRequestUncheckedCreateWithoutItemsInput = {
  id?: string
  sourceId: string
  destinationId: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type TransferRequestCreateOrConnectWithoutItemsInput = {
  where: Prisma.TransferRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.TransferRequestCreateWithoutItemsInput, Prisma.TransferRequestUncheckedCreateWithoutItemsInput>
}

export type TransferRequestUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.TransferRequestUpdateWithoutItemsInput, Prisma.TransferRequestUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.TransferRequestCreateWithoutItemsInput, Prisma.TransferRequestUncheckedCreateWithoutItemsInput>
  where?: Prisma.TransferRequestWhereInput
}

export type TransferRequestUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.TransferRequestWhereInput
  data: Prisma.XOR<Prisma.TransferRequestUpdateWithoutItemsInput, Prisma.TransferRequestUncheckedUpdateWithoutItemsInput>
}

export type TransferRequestUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.WarehouseUpdateOneRequiredWithoutTransferRequestsSourceNestedInput
  destination?: Prisma.WarehouseUpdateOneRequiredWithoutTransferRequestsDestinationNestedInput
}

export type TransferRequestUncheckedUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TransferRequestCreateManySourceInput = {
  id?: string
  destinationId: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type TransferRequestCreateManyDestinationInput = {
  id?: string
  sourceId: string
  reference: string
  note?: string | null
  createdAt?: Date | string
  syncedAt?: Date | string | null
  deletedAt?: Date | string | null
  deviceId?: string | null
}

export type TransferRequestUpdateWithoutSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destination?: Prisma.WarehouseUpdateOneRequiredWithoutTransferRequestsDestinationNestedInput
  items?: Prisma.TransferItemUpdateManyWithoutTransferNestedInput
}

export type TransferRequestUncheckedUpdateWithoutSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  items?: Prisma.TransferItemUncheckedUpdateManyWithoutTransferNestedInput
}

export type TransferRequestUncheckedUpdateManyWithoutSourceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  destinationId?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TransferRequestUpdateWithoutDestinationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.WarehouseUpdateOneRequiredWithoutTransferRequestsSourceNestedInput
  items?: Prisma.TransferItemUpdateManyWithoutTransferNestedInput
}

export type TransferRequestUncheckedUpdateWithoutDestinationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  items?: Prisma.TransferItemUncheckedUpdateManyWithoutTransferNestedInput
}

export type TransferRequestUncheckedUpdateManyWithoutDestinationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sourceId?: Prisma.StringFieldUpdateOperationsInput | string
  reference?: Prisma.StringFieldUpdateOperationsInput | string
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  deviceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type TransferRequestCountOutputType
 */

export type TransferRequestCountOutputType = {
  items: number
}

export type TransferRequestCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | TransferRequestCountOutputTypeCountItemsArgs
}

/**
 * TransferRequestCountOutputType without action
 */
export type TransferRequestCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequestCountOutputType
   */
  select?: Prisma.TransferRequestCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TransferRequestCountOutputType without action
 */
export type TransferRequestCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransferItemWhereInput
}


export type TransferRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sourceId?: boolean
  destinationId?: boolean
  reference?: boolean
  note?: boolean
  createdAt?: boolean
  syncedAt?: boolean
  deletedAt?: boolean
  deviceId?: boolean
  source?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
  items?: boolean | Prisma.TransferRequest$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.TransferRequestCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transferRequest"]>

export type TransferRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sourceId?: boolean
  destinationId?: boolean
  reference?: boolean
  note?: boolean
  createdAt?: boolean
  syncedAt?: boolean
  deletedAt?: boolean
  deviceId?: boolean
  source?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transferRequest"]>

export type TransferRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sourceId?: boolean
  destinationId?: boolean
  reference?: boolean
  note?: boolean
  createdAt?: boolean
  syncedAt?: boolean
  deletedAt?: boolean
  deviceId?: boolean
  source?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transferRequest"]>

export type TransferRequestSelectScalar = {
  id?: boolean
  sourceId?: boolean
  destinationId?: boolean
  reference?: boolean
  note?: boolean
  createdAt?: boolean
  syncedAt?: boolean
  deletedAt?: boolean
  deviceId?: boolean
}

export type TransferRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sourceId" | "destinationId" | "reference" | "note" | "createdAt" | "syncedAt" | "deletedAt" | "deviceId", ExtArgs["result"]["transferRequest"]>
export type TransferRequestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  source?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
  items?: boolean | Prisma.TransferRequest$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.TransferRequestCountOutputTypeDefaultArgs<ExtArgs>
}
export type TransferRequestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  source?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}
export type TransferRequestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  source?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
  destination?: boolean | Prisma.WarehouseDefaultArgs<ExtArgs>
}

export type $TransferRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TransferRequest"
  objects: {
    source: Prisma.$WarehousePayload<ExtArgs>
    destination: Prisma.$WarehousePayload<ExtArgs>
    items: Prisma.$TransferItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sourceId: string
    destinationId: string
    reference: string
    note: string | null
    createdAt: Date
    syncedAt: Date | null
    deletedAt: Date | null
    deviceId: string | null
  }, ExtArgs["result"]["transferRequest"]>
  composites: {}
}

export type TransferRequestGetPayload<S extends boolean | null | undefined | TransferRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload, S>

export type TransferRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TransferRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TransferRequestCountAggregateInputType | true
  }

export interface TransferRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TransferRequest'], meta: { name: 'TransferRequest' } }
  /**
   * Find zero or one TransferRequest that matches the filter.
   * @param {TransferRequestFindUniqueArgs} args - Arguments to find a TransferRequest
   * @example
   * // Get one TransferRequest
   * const transferRequest = await prisma.transferRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TransferRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, TransferRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TransferRequestClient<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TransferRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TransferRequestFindUniqueOrThrowArgs} args - Arguments to find a TransferRequest
   * @example
   * // Get one TransferRequest
   * const transferRequest = await prisma.transferRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TransferRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TransferRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransferRequestClient<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TransferRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransferRequestFindFirstArgs} args - Arguments to find a TransferRequest
   * @example
   * // Get one TransferRequest
   * const transferRequest = await prisma.transferRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TransferRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, TransferRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__TransferRequestClient<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TransferRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransferRequestFindFirstOrThrowArgs} args - Arguments to find a TransferRequest
   * @example
   * // Get one TransferRequest
   * const transferRequest = await prisma.transferRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TransferRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TransferRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransferRequestClient<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TransferRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransferRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TransferRequests
   * const transferRequests = await prisma.transferRequest.findMany()
   * 
   * // Get first 10 TransferRequests
   * const transferRequests = await prisma.transferRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const transferRequestWithIdOnly = await prisma.transferRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TransferRequestFindManyArgs>(args?: Prisma.SelectSubset<T, TransferRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TransferRequest.
   * @param {TransferRequestCreateArgs} args - Arguments to create a TransferRequest.
   * @example
   * // Create one TransferRequest
   * const TransferRequest = await prisma.transferRequest.create({
   *   data: {
   *     // ... data to create a TransferRequest
   *   }
   * })
   * 
   */
  create<T extends TransferRequestCreateArgs>(args: Prisma.SelectSubset<T, TransferRequestCreateArgs<ExtArgs>>): Prisma.Prisma__TransferRequestClient<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TransferRequests.
   * @param {TransferRequestCreateManyArgs} args - Arguments to create many TransferRequests.
   * @example
   * // Create many TransferRequests
   * const transferRequest = await prisma.transferRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TransferRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, TransferRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TransferRequests and returns the data saved in the database.
   * @param {TransferRequestCreateManyAndReturnArgs} args - Arguments to create many TransferRequests.
   * @example
   * // Create many TransferRequests
   * const transferRequest = await prisma.transferRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TransferRequests and only return the `id`
   * const transferRequestWithIdOnly = await prisma.transferRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TransferRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TransferRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TransferRequest.
   * @param {TransferRequestDeleteArgs} args - Arguments to delete one TransferRequest.
   * @example
   * // Delete one TransferRequest
   * const TransferRequest = await prisma.transferRequest.delete({
   *   where: {
   *     // ... filter to delete one TransferRequest
   *   }
   * })
   * 
   */
  delete<T extends TransferRequestDeleteArgs>(args: Prisma.SelectSubset<T, TransferRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__TransferRequestClient<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TransferRequest.
   * @param {TransferRequestUpdateArgs} args - Arguments to update one TransferRequest.
   * @example
   * // Update one TransferRequest
   * const transferRequest = await prisma.transferRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TransferRequestUpdateArgs>(args: Prisma.SelectSubset<T, TransferRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__TransferRequestClient<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TransferRequests.
   * @param {TransferRequestDeleteManyArgs} args - Arguments to filter TransferRequests to delete.
   * @example
   * // Delete a few TransferRequests
   * const { count } = await prisma.transferRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TransferRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, TransferRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TransferRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransferRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TransferRequests
   * const transferRequest = await prisma.transferRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TransferRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, TransferRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TransferRequests and returns the data updated in the database.
   * @param {TransferRequestUpdateManyAndReturnArgs} args - Arguments to update many TransferRequests.
   * @example
   * // Update many TransferRequests
   * const transferRequest = await prisma.transferRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TransferRequests and only return the `id`
   * const transferRequestWithIdOnly = await prisma.transferRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TransferRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TransferRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TransferRequest.
   * @param {TransferRequestUpsertArgs} args - Arguments to update or create a TransferRequest.
   * @example
   * // Update or create a TransferRequest
   * const transferRequest = await prisma.transferRequest.upsert({
   *   create: {
   *     // ... data to create a TransferRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TransferRequest we want to update
   *   }
   * })
   */
  upsert<T extends TransferRequestUpsertArgs>(args: Prisma.SelectSubset<T, TransferRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__TransferRequestClient<runtime.Types.Result.GetResult<Prisma.$TransferRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TransferRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransferRequestCountArgs} args - Arguments to filter TransferRequests to count.
   * @example
   * // Count the number of TransferRequests
   * const count = await prisma.transferRequest.count({
   *   where: {
   *     // ... the filter for the TransferRequests we want to count
   *   }
   * })
  **/
  count<T extends TransferRequestCountArgs>(
    args?: Prisma.Subset<T, TransferRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TransferRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TransferRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransferRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TransferRequestAggregateArgs>(args: Prisma.Subset<T, TransferRequestAggregateArgs>): Prisma.PrismaPromise<GetTransferRequestAggregateType<T>>

  /**
   * Group by TransferRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransferRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TransferRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TransferRequestGroupByArgs['orderBy'] }
      : { orderBy?: TransferRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TransferRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTransferRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TransferRequest model
 */
readonly fields: TransferRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TransferRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TransferRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  source<T extends Prisma.WarehouseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WarehouseDefaultArgs<ExtArgs>>): Prisma.Prisma__WarehouseClient<runtime.Types.Result.GetResult<Prisma.$WarehousePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  destination<T extends Prisma.WarehouseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WarehouseDefaultArgs<ExtArgs>>): Prisma.Prisma__WarehouseClient<runtime.Types.Result.GetResult<Prisma.$WarehousePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  items<T extends Prisma.TransferRequest$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TransferRequest$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransferItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TransferRequest model
 */
export interface TransferRequestFieldRefs {
  readonly id: Prisma.FieldRef<"TransferRequest", 'String'>
  readonly sourceId: Prisma.FieldRef<"TransferRequest", 'String'>
  readonly destinationId: Prisma.FieldRef<"TransferRequest", 'String'>
  readonly reference: Prisma.FieldRef<"TransferRequest", 'String'>
  readonly note: Prisma.FieldRef<"TransferRequest", 'String'>
  readonly createdAt: Prisma.FieldRef<"TransferRequest", 'DateTime'>
  readonly syncedAt: Prisma.FieldRef<"TransferRequest", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"TransferRequest", 'DateTime'>
  readonly deviceId: Prisma.FieldRef<"TransferRequest", 'String'>
}
    

// Custom InputTypes
/**
 * TransferRequest findUnique
 */
export type TransferRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
  /**
   * Filter, which TransferRequest to fetch.
   */
  where: Prisma.TransferRequestWhereUniqueInput
}

/**
 * TransferRequest findUniqueOrThrow
 */
export type TransferRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
  /**
   * Filter, which TransferRequest to fetch.
   */
  where: Prisma.TransferRequestWhereUniqueInput
}

/**
 * TransferRequest findFirst
 */
export type TransferRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
  /**
   * Filter, which TransferRequest to fetch.
   */
  where?: Prisma.TransferRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransferRequests to fetch.
   */
  orderBy?: Prisma.TransferRequestOrderByWithRelationInput | Prisma.TransferRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TransferRequests.
   */
  cursor?: Prisma.TransferRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransferRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransferRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TransferRequests.
   */
  distinct?: Prisma.TransferRequestScalarFieldEnum | Prisma.TransferRequestScalarFieldEnum[]
}

/**
 * TransferRequest findFirstOrThrow
 */
export type TransferRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
  /**
   * Filter, which TransferRequest to fetch.
   */
  where?: Prisma.TransferRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransferRequests to fetch.
   */
  orderBy?: Prisma.TransferRequestOrderByWithRelationInput | Prisma.TransferRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TransferRequests.
   */
  cursor?: Prisma.TransferRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransferRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransferRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TransferRequests.
   */
  distinct?: Prisma.TransferRequestScalarFieldEnum | Prisma.TransferRequestScalarFieldEnum[]
}

/**
 * TransferRequest findMany
 */
export type TransferRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
  /**
   * Filter, which TransferRequests to fetch.
   */
  where?: Prisma.TransferRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransferRequests to fetch.
   */
  orderBy?: Prisma.TransferRequestOrderByWithRelationInput | Prisma.TransferRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TransferRequests.
   */
  cursor?: Prisma.TransferRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransferRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransferRequests.
   */
  skip?: number
  distinct?: Prisma.TransferRequestScalarFieldEnum | Prisma.TransferRequestScalarFieldEnum[]
}

/**
 * TransferRequest create
 */
export type TransferRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
  /**
   * The data needed to create a TransferRequest.
   */
  data: Prisma.XOR<Prisma.TransferRequestCreateInput, Prisma.TransferRequestUncheckedCreateInput>
}

/**
 * TransferRequest createMany
 */
export type TransferRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TransferRequests.
   */
  data: Prisma.TransferRequestCreateManyInput | Prisma.TransferRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TransferRequest createManyAndReturn
 */
export type TransferRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * The data used to create many TransferRequests.
   */
  data: Prisma.TransferRequestCreateManyInput | Prisma.TransferRequestCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TransferRequest update
 */
export type TransferRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
  /**
   * The data needed to update a TransferRequest.
   */
  data: Prisma.XOR<Prisma.TransferRequestUpdateInput, Prisma.TransferRequestUncheckedUpdateInput>
  /**
   * Choose, which TransferRequest to update.
   */
  where: Prisma.TransferRequestWhereUniqueInput
}

/**
 * TransferRequest updateMany
 */
export type TransferRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TransferRequests.
   */
  data: Prisma.XOR<Prisma.TransferRequestUpdateManyMutationInput, Prisma.TransferRequestUncheckedUpdateManyInput>
  /**
   * Filter which TransferRequests to update
   */
  where?: Prisma.TransferRequestWhereInput
  /**
   * Limit how many TransferRequests to update.
   */
  limit?: number
}

/**
 * TransferRequest updateManyAndReturn
 */
export type TransferRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * The data used to update TransferRequests.
   */
  data: Prisma.XOR<Prisma.TransferRequestUpdateManyMutationInput, Prisma.TransferRequestUncheckedUpdateManyInput>
  /**
   * Filter which TransferRequests to update
   */
  where?: Prisma.TransferRequestWhereInput
  /**
   * Limit how many TransferRequests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TransferRequest upsert
 */
export type TransferRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
  /**
   * The filter to search for the TransferRequest to update in case it exists.
   */
  where: Prisma.TransferRequestWhereUniqueInput
  /**
   * In case the TransferRequest found by the `where` argument doesn't exist, create a new TransferRequest with this data.
   */
  create: Prisma.XOR<Prisma.TransferRequestCreateInput, Prisma.TransferRequestUncheckedCreateInput>
  /**
   * In case the TransferRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TransferRequestUpdateInput, Prisma.TransferRequestUncheckedUpdateInput>
}

/**
 * TransferRequest delete
 */
export type TransferRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
  /**
   * Filter which TransferRequest to delete.
   */
  where: Prisma.TransferRequestWhereUniqueInput
}

/**
 * TransferRequest deleteMany
 */
export type TransferRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TransferRequests to delete
   */
  where?: Prisma.TransferRequestWhereInput
  /**
   * Limit how many TransferRequests to delete.
   */
  limit?: number
}

/**
 * TransferRequest.items
 */
export type TransferRequest$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferItem
   */
  select?: Prisma.TransferItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferItem
   */
  omit?: Prisma.TransferItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferItemInclude<ExtArgs> | null
  where?: Prisma.TransferItemWhereInput
  orderBy?: Prisma.TransferItemOrderByWithRelationInput | Prisma.TransferItemOrderByWithRelationInput[]
  cursor?: Prisma.TransferItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransferItemScalarFieldEnum | Prisma.TransferItemScalarFieldEnum[]
}

/**
 * TransferRequest without action
 */
export type TransferRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransferRequest
   */
  select?: Prisma.TransferRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransferRequest
   */
  omit?: Prisma.TransferRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransferRequestInclude<ExtArgs> | null
}
