import { Database } from 'sql.js'
import { randomUUID } from 'crypto'
import { QueueService } from './queue.service'
import { saveDb } from '../localDb'
import { ProductLocationCloudService } from './product-location-cloud.service'
import { StockTransactionCloudService } from './stock-transaction-cloud.service'

export interface ReturnDto {
  transactionId: string
  storeId: string
  returnNumber: string // Generated by frontend or backend? Let's assume passed or generated here.
  // Actually usually Backend generates number. But offline? Frontend might generate UUID, Backend generates Number?
  // Let's expect 'returnNumber' or 'code' from frontend for consistency, or generate if missing.
  totalRefund: string
  reason?: string
  createdBy: string
  items: ReturnItemDto[]
}

export interface ReturnItemDto {
  transactionItemId: string
  productId: string
  quantity: number
  refundPrice: string
  restock: boolean
}

export class ReturnService {
  constructor(
    private db: Database,
    private queueService: QueueService,
    private stockTransactionService: StockTransactionCloudService,
    private productLocationService: ProductLocationCloudService
  ) {}

  async createReturn(data: ReturnDto): Promise<any> {
    const id = randomUUID()
    const now = Date.now()
    const nowIso = new Date(now).toISOString()

    const returnNumber = data.returnNumber || `RET-${now}`

    // 1. Queue Return Header INSERT
    if (this.queueService) {
      await this.queueService.add('INSERT', 'transaction_return', {
        id,
        transaction_id: data.transactionId,
        return_number: returnNumber,
        store_id: data.storeId,
        total_refund: data.totalRefund,
        reason: data.reason ?? null,
        created_by: data.createdBy,
        created_at: nowIso,
        updated_at: nowIso
      })
    }

    // 2. Insert Locally
    this.db.run(
      'INSERT INTO transaction_return (id, transaction_id, return_number, store_id, total_refund, reason, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
      [
        id,
        data.transactionId,
        returnNumber,
        data.storeId,
        data.totalRefund,
        data.reason ?? null,
        data.createdBy,
        now,
        now
      ]
    )

    // 3. Process Items
    for (const item of data.items) {
      const itemId = randomUUID()

      // 3a. Queue Item
      if (this.queueService) {
        await this.queueService.add('INSERT', 'transaction_return_item', {
          id: itemId,
          return_id: id,
          transaction_item_id: item.transactionItemId,
          product_id: item.productId,
          quantity: item.quantity,
          refund_price: item.refundPrice,
          restock: item.restock ? 1 : 0,
          created_at: nowIso,
          updated_at: nowIso
        })
      }

      // 3b. Insert Item Locally
      this.db.run(
        'INSERT INTO transaction_return_item (id, return_id, transaction_item_id, product_id, quantity, refund_price, restock, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
        [
          itemId,
          id,
          item.transactionItemId,
          item.productId,
          item.quantity,
          item.refundPrice,
          item.restock ? 1 : 0,
          now,
          now
        ]
      )

      // 3c. Stock Adjustment (if restock is true)
      if (item.restock) {
        // Create stock transaction
        await this.stockTransactionService.create({
          productId: item.productId,
          storeId: data.storeId,
          type: 'RETURN', // Need to ensure type exists or is string
          quantity: item.quantity,
          reference: returnNumber,
          performedBy: data.createdBy
        })

        // Add back to product_location
        await this.productLocationService.adjustQuantity(
          item.productId,
          data.storeId,
          item.quantity // Add (positive)
        )
      }
    }

    saveDb(this.db)
    return { id, returnNumber }
  }

  async getReturnsByTransactionId(transactionId: string): Promise<any[]> {
    const stmt = this.db.prepare(
      'SELECT * FROM transaction_return WHERE transaction_id = ? AND deleted_at IS NULL ORDER BY created_at DESC'
    )
    stmt.bind([transactionId])
    const results: any[] = []
    while (stmt.step()) {
      const row = stmt.getAsObject()
      // Fetch items
      const items = await this.getReturnItems(row.id as string)
      results.push({ ...row, items })
    }
    stmt.free()
    return results
  }

  async getReturnItems(returnId: string): Promise<any[]> {
    const stmt = this.db.prepare('SELECT * FROM transaction_return_item WHERE return_id = ?')
    stmt.bind([returnId])
    const results: any[] = []
    while (stmt.step()) {
      results.push(stmt.getAsObject())
    }
    stmt.free()
    return results
  }
}
