import { randomUUID } from 'crypto'
import { QueueService } from './queue.service'
import { ProductLocationCloudService } from './product-location-cloud.service'
import { StockTransactionCloudService } from './stock-transaction-cloud.service'
import { getCloudDb } from './cloud-db.service'

export interface ReturnDto {
  transactionId: string
  storeId: string
  returnNumber: string // Generated by frontend or backend? Let's assume passed or generated here.
  // Actually usually Backend generates number. But offline? Frontend might generate UUID, Backend generates Number?
  // Let's expect 'returnNumber' or 'code' from frontend for consistency, or generate if missing.
  totalRefund: string
  reason?: string
  createdBy: string
  items: ReturnItemDto[]
}

export interface ReturnItemDto {
  transactionItemId: string
  productId: string
  quantity: number
  refundPrice: string
  restock: boolean
}

export class ReturnService {
  constructor(
    private queueService: QueueService,
    private stockTransactionService: StockTransactionCloudService,
    private productLocationService: ProductLocationCloudService
  ) {}

  async createReturn(data: ReturnDto): Promise<any> {
    const id = randomUUID()
    const now = Date.now()
    const nowIso = new Date(now).toISOString()

    const returnNumber = data.returnNumber || `RET-${now}`

    // 1. Queue Return Header INSERT
    await this.queueService.add('INSERT', 'transaction_return', {
      id,
      transaction_id: data.transactionId,
      return_number: returnNumber,
      store_id: data.storeId,
      total_refund: data.totalRefund,
      reason: data.reason ?? null,
      created_by: data.createdBy,
      created_at: nowIso,
      updated_at: nowIso
    })

    // 2. Process Items
    for (const item of data.items) {
      const itemId = randomUUID()

      // 2a. Queue Item INSERT
      await this.queueService.add('INSERT', 'transaction_return_item', {
        id: itemId,
        return_id: id,
        transaction_item_id: item.transactionItemId,
        product_id: item.productId,
        quantity: item.quantity,
        refund_price: item.refundPrice,
        restock: item.restock ? 1 : 0,
        created_at: nowIso,
        updated_at: nowIso
      })

      // 2b. Stock Adjustment (if restock is true)
      if (item.restock) {
        await this.stockTransactionService.create({
          productId: item.productId,
          storeId: data.storeId,
          type: 'RETURN',
          quantity: item.quantity,
          reference: returnNumber,
          performedBy: data.createdBy
        })

        await this.productLocationService.adjustQuantity(
          item.productId,
          data.storeId,
          item.quantity
        )
      }
    }

    // 3. Queue transaction item quantity updates
    try {
      const pool = getCloudDb().getPool()

      for (const item of data.items) {
        const result = await pool.query(
          'SELECT quantity, display_quantity, price FROM transaction_items WHERE id = $1',
          [item.transactionItemId]
        )

        if (result.rows.length > 0) {
          const row = result.rows[0]
          const currentQty = Number(row.quantity)
          const currentDisplayQty = Number(row.display_quantity) || currentQty
          const newQty = currentQty - item.quantity
          const conversionFactor =
            currentQty > 0 && currentDisplayQty > 0 ? currentQty / currentDisplayQty : 1
          const newDisplayQty = newQty / conversionFactor

          await this.queueService.add('UPDATE', 'transaction_items', {
            id: item.transactionItemId,
            quantity: newQty,
            display_quantity: newDisplayQty,
            updated_at: nowIso
          })
        }
      }

      // 4. Queue transaction totals update
      const itemsResult = await pool.query(
        'SELECT id, quantity, price FROM transaction_items WHERE transaction_id = $1',
        [data.transactionId]
      )

      let newSubtotal = 0
      for (const row of itemsResult.rows) {
        const returnedItem = data.items.find((i) => i.transactionItemId === row.id)
        const qty = returnedItem
          ? Number(row.quantity) - returnedItem.quantity
          : Number(row.quantity)
        newSubtotal += qty * Number(row.price)
      }

      const txnResult = await pool.query('SELECT discount FROM transactions WHERE id = $1', [
        data.transactionId
      ])
      const discount = Number(txnResult.rows[0]?.discount) || 0
      const newTotal = newSubtotal - discount

      await this.queueService.add('UPDATE', 'transactions', {
        id: data.transactionId,
        subtotal: newSubtotal.toString(),
        total: newTotal.toString(),
        updated_at: nowIso
      })
    } catch (error) {
      console.error('[ReturnService] Failed to queue transaction updates:', error)
    }

    return { id, returnNumber }
  }

  async getReturnsByTransactionId(transactionId: string): Promise<any[]> {
    try {
      const pool = getCloudDb().getPool()
      const result = await pool.query(
        'SELECT * FROM transaction_return WHERE transaction_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC',
        [transactionId]
      )

      const returns: any[] = []
      for (const row of result.rows) {
        const items = await this.getReturnItems(row.id)
        returns.push({ ...row, items })
      }
      return returns
    } catch (error) {
      console.error('[ReturnService] getReturnsByTransactionId error:', error)
      return []
    }
  }

  async getReturnItems(returnId: string): Promise<any[]> {
    try {
      const pool = getCloudDb().getPool()
      const result = await pool.query(
        'SELECT * FROM transaction_return_item WHERE return_id = $1',
        [returnId]
      )
      return result.rows
    } catch (error) {
      console.error('[ReturnService] getReturnItems error:', error)
      return []
    }
  }
}
