import { randomUUID } from 'crypto'
import { QueueService } from './queue.service'
import { ProductLocationCloudService } from './product-location-cloud.service'
import { StockTransactionCloudService } from './stock-transaction-cloud.service'
import { getCloudDb } from './cloud-db.service'

export interface ReturnDto {
  transactionId: string
  storeId: string
  returnNumber: string // Generated by frontend or backend? Let's assume passed or generated here.
  // Actually usually Backend generates number. But offline? Frontend might generate UUID, Backend generates Number?
  // Let's expect 'returnNumber' or 'code' from frontend for consistency, or generate if missing.
  totalRefund: string
  reason?: string
  createdBy: string
  items: ReturnItemDto[]
}

export interface ReturnItemDto {
  transactionItemId: string
  productId: string
  quantity: number
  refundPrice: string
  restock: boolean
}

export class ReturnService {
  constructor(
    private queueService: QueueService,
    private stockTransactionService: StockTransactionCloudService,
    private productLocationService: ProductLocationCloudService
  ) {}

  async createReturn(data: ReturnDto): Promise<any> {
    const id = randomUUID()
    const now = Date.now()
    const nowIso = new Date(now).toISOString()

    const returnNumber = data.returnNumber || `RET-${now}`

    // 1. Queue Return Header INSERT
    await this.queueService.add('INSERT', 'transaction_return', {
      id,
      transaction_id: data.transactionId,
      return_number: returnNumber,
      store_id: data.storeId,
      total_refund: data.totalRefund,
      reason: data.reason ?? null,
      created_by: data.createdBy,
      created_at: nowIso,
      updated_at: nowIso
    })

    // Fetch transaction items for reference
    const pool = getCloudDb().getPool()
    const txnItemsRes = await pool.query(
      'SELECT id, product_name, uom_code, display_quantity, quantity FROM transaction_items WHERE transaction_id = $1',
      [data.transactionId]
    )
    const txnItemMap = new Map<string, any>(txnItemsRes.rows.map((r) => [r.id, r]))

    // 2. Process Items
    for (const item of data.items) {
      const itemId = randomUUID()

      // Lookup original item details
      const txnItem = txnItemMap.get(item.transactionItemId)
      let productName = ''
      let uomCode = 'PCS'
      let conversionFactor = 1
      let displayQuantity = item.quantity

      if (txnItem) {
        productName = txnItem.product_name || ''
        uomCode = txnItem.uomCode || txnItem.uom_code || 'PCS'
        const baseQty = Number(txnItem.quantity)
        const dispQty = Number(txnItem.displayQuantity || txnItem.display_quantity) || baseQty
        conversionFactor = baseQty > 0 && dispQty > 0 ? baseQty / dispQty : 1
        displayQuantity = conversionFactor > 0 ? item.quantity / conversionFactor : item.quantity
      }

      // 2a. Queue Item INSERT
      await this.queueService.add('INSERT', 'transaction_return_item', {
        id: itemId,
        return_id: id,
        transaction_item_id: item.transactionItemId,
        product_id: item.productId,
        quantity: item.quantity,
        refund_price: item.refundPrice,
        restock: item.restock ? 1 : 0,
        product_name: productName,
        uom_code: uomCode,
        display_quantity: displayQuantity,
        conversion_factor: conversionFactor,
        created_at: nowIso,
        updated_at: nowIso
      })

      // 2b. Stock Adjustment (if restock is true)
      if (item.restock) {
        await this.stockTransactionService.create({
          productId: item.productId,
          storeId: data.storeId,
          type: 'RETURN',
          quantity: item.quantity,
          reference: returnNumber,
          performedBy: data.createdBy
        })

        await this.productLocationService.adjustQuantity(
          item.productId,
          data.storeId,
          item.quantity
        )
      }
    }

    // 3. Queue transaction item quantity updates
    try {
      for (const item of data.items) {
        // We already have the transaction item data in txnItemMap, but let's re-query to be safe/consistent with original logic
        // Or we can reuse txnItemMap since we just fetched it.
        // However, the original logic re-queries by ID. Let's keep it robust but use pool we already got.
        // Actually, let's reuse txnItemMap logic or just keep original logic for minimal disturbance.
        // But we need to use pool.
        
        const txnItem = txnItemMap.get(item.transactionItemId)
        if (txnItem) {
          const currentQty = Number(txnItem.quantity)
          const currentDisplayQty = Number(txnItem.displayQuantity || txnItem.display_quantity) || currentQty
          const newQty = currentQty - item.quantity
          const conversionFactor =
            currentQty > 0 && currentDisplayQty > 0 ? currentQty / currentDisplayQty : 1
          const newDisplayQty = newQty / conversionFactor

          await this.queueService.add('UPDATE', 'transaction_items', {
            id: item.transactionItemId,
            quantity: newQty,
            display_quantity: newDisplayQty,
            updated_at: nowIso
          })
        }
      }

      // 4. Queue transaction totals update
      // We can reuse txnItemMap for this calculation too, but we need updated quantities.
      // The original logic queries DB again. Since we are in a loop, let's stick to original logic structure but clean it up.
      // Actually, step 4 queries ALL items items again.

      const itemsResult = await pool.query(
        'SELECT id, quantity, price FROM transaction_items WHERE transaction_id = $1',
        [data.transactionId]
      )

      let newSubtotal = 0
      for (const row of itemsResult.rows) {
        const returnedItem = data.items.find((i) => i.transactionItemId === row.id)
        const qty = returnedItem
          ? Number(row.quantity) - returnedItem.quantity
          : Number(row.quantity)
        newSubtotal += qty * Number(row.price)
      }

      const txnResult = await pool.query('SELECT discount FROM transactions WHERE id = $1', [
        data.transactionId
      ])
      const discount = Number(txnResult.rows[0]?.discount) || 0
      const newTotal = newSubtotal - discount

      await this.queueService.add('UPDATE', 'transactions', {
        id: data.transactionId,
        subtotal: newSubtotal.toString(),
        total: newTotal.toString(),
        updated_at: nowIso
      })
    } catch (error) {
      console.error('[ReturnService] Failed to queue transaction updates:', error)
    }

    return { id, returnNumber }
  }

  async getReturnsByTransactionId(transactionId: string): Promise<any[]> {
    try {
      const pool = getCloudDb().getPool()
      const result = await pool.query(
        'SELECT * FROM transaction_return WHERE transaction_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC',
        [transactionId]
      )

      const returns: any[] = []
      for (const row of result.rows) {
        const items = await this.getReturnItems(row.id)
        returns.push({ ...row, items })
      }
      return returns
    } catch (error) {
      console.error('[ReturnService] getReturnsByTransactionId error:', error)
      return []
    }
  }

  async getReturnItems(returnId: string): Promise<any[]> {
    try {
      const pool = getCloudDb().getPool()
      const result = await pool.query(
        'SELECT * FROM transaction_return_item WHERE return_id = $1',
        [returnId]
      )
      return result.rows
    } catch (error) {
      console.error('[ReturnService] getReturnItems error:', error)
      return []
    }
  }
}
