
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model Permission
 * 
 */
export type Permission = Prisma.PermissionModel
/**
 * Model UserRole
 * 
 */
export type UserRole = Prisma.UserRoleModel
/**
 * Model RolePermission
 * 
 */
export type RolePermission = Prisma.RolePermissionModel
/**
 * Model Store
 * 
 */
export type Store = Prisma.StoreModel
/**
 * Model Warehouse
 * 
 */
export type Warehouse = Prisma.WarehouseModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Supplier
 * 
 */
export type Supplier = Prisma.SupplierModel
/**
 * Model ProductPrice
 * 
 */
export type ProductPrice = Prisma.ProductPriceModel
/**
 * Model ProductLocation
 * 
 */
export type ProductLocation = Prisma.ProductLocationModel
/**
 * Model Batch
 * 
 */
export type Batch = Prisma.BatchModel
/**
 * Model Customer
 * 
 */
export type Customer = Prisma.CustomerModel
/**
 * Model StockTransaction
 * 
 */
export type StockTransaction = Prisma.StockTransactionModel
/**
 * Model StockAdjustment
 * 
 */
export type StockAdjustment = Prisma.StockAdjustmentModel
/**
 * Model PurchaseOrder
 * 
 */
export type PurchaseOrder = Prisma.PurchaseOrderModel
/**
 * Model PurchaseOrderItem
 * 
 */
export type PurchaseOrderItem = Prisma.PurchaseOrderItemModel
/**
 * Model TransferRequest
 * 
 */
export type TransferRequest = Prisma.TransferRequestModel
/**
 * Model TransferItem
 * 
 */
export type TransferItem = Prisma.TransferItemModel
/**
 * Model Transactions
 * 
 */
export type Transactions = Prisma.TransactionsModel
/**
 * Model TransactionItems
 * 
 */
export type TransactionItems = Prisma.TransactionItemsModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
